### ISSUE TITLE
Kapacitor rule graph isn't displaying the threshold value

### ISSUE THREAD

**Issue by rkuchan** [influxdata/chronograf#1041]
In previous versions, I was able to see the threshold value on the graph on the alert creation page. Now, the graph hops around when I set a threshold and I can't see the value on the graph.

(I think I've seen this before. Maybe related to https://github.com/influxdata/chronograf/pull/926?)

### Repro steps

On the rules page:

#### Step 1: Select a Time Series
I used:
```
SELECT "usage_idle" FROM "telegraf"."autogen"."cpu" WHERE time > now() - 15m
```

#### Step 2: Define a simple threshold rule
I did:
![image](https://cloud.githubusercontent.com/assets/8750814/24170331/cecf9150-0e3d-11e7-9e42-35bd28f0522e.png)

#### Step 3: Look at the graph and feel a deep emptiness

![image](https://cloud.githubusercontent.com/assets/8750814/24170361/e712c93a-0e3d-11e7-85dd-ea9849d4689b.png)

**Comment by goller** [comment]
@rkuchan I'm not able to reproduce this on master.

**Comment by nhaugo** [comment]
Looks like this might only be an issue on chrome.

**Comment by jaredscheib** [comment]
Might be related to https://github.com/influxdata/chronograf/pull/882 also

**Comment by lukevmorris** [comment]
This is what I get after following the above reproduction steps on master:
![screen shot 2017-03-30 at 9 42 49 am](https://cloud.githubusercontent.com/assets/1438089/24515707/439d2a1a-152d-11e7-822a-68f717f88cdd.png)

**Comment by lukevmorris** [comment]
Ok, found it. The graph will look fine if you're creating or updating a RuleAlert, but the issue seems to appear after refreshing the page, and only if the defined threshold is far lower or far greater than the nominal range of values. I believe that Dygraphs is correctly drawing the overlay, but is not recalculating the range of the y-axis to show it.

Additionally, after reloading the page and focusing the threshold input, simply moving your text cursor left and right will force the graph to recalculate and make the overlay appear. Fixing this is simple, and I have a PR incoming.
