### ISSUE TITLE
Dashboard empty state

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#1052]
In anticipation of dashboard editing, it will be possible for a user to see a dashboard with 0 graphs (assuming they delete all the graphs).

Wanted to start a little discussion around the UX here.

Here's a mockup of a dash empty state:
![screen shot 2017-03-23 at 12 20 11 pm](https://cloud.githubusercontent.com/assets/2433762/24266193/31d39c20-0fc3-11e7-9864-8513ba03daa3.png)

**Comment by cryptoquick** [comment]
Is it preferable to just use this instead of pre-populating with an initial graph? Another option is to keep a pre-populated initial graph in there always, and even if the first graph is deleted a new blank graph is added.

This looks very nice though, and I think we should do it. I just want to be clear that the composition shows the route we should go, instead of alternative UX.
