### ISSUE TITLE
Field keys returning from server come back in wrong order

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1158]
If there is more than one query, a different single stat is currently displayed under different conditions or on different pages, for a cell.

**Comment by jaredscheib** [comment]
@jackzampolin is interested in this outcome as well.

**Comment by nhaugo** [comment]
The is multiple fields are selected the first in the list should always be what is display as the single stat, e.g. SELECT foo,bar,baz from cpu. 

The single stat should aways be "foo" in this case.

@jackzampolin thoughts

**Comment by nhaugo** [comment]
@rkuchan Do we have info about the viz types in the docs, if so we will want to document this behavior.

**Comment by rkuchan** [comment]
I'll make sure to add this to the Dashboard guide

**Comment by timraymond** [comment]
Using the first field appears to be the current behavior when creating a single stat:

![Screencap showing desired behavior](http://g.recordit.co/Zz8WBcmISZ.gif)

For fields A and B, I first added A, then B, removed A, added A, then removed B to arrive at the initial state. It displays the first field in the query.

I think this can be closed unless someone can provide repro steps showing otherwise.

**Comment by lukevmorris** [comment]
After further diagnosis, it appears that Single Stat is behaving as expected. Given a query with two fields, it will display the most current value for the first field.

However, occasionally when saving changes to a cell, the field keys in the queryConfig will come back from the server in a different order than when they were submitted. This means that if we submit

```
SELECT "usage_idle", "usage_user" FROM ...
```

it's possible to receive

```
SELECT "usage_user", "usage_idle" FROM ...
```


When validating the query at `/sources/1/queries`, the fields come back in the same order.
But when PATCHing a cell, the fields can come back in a different order.

This means that you may see one stat in the CEO but another stat when returning to the dashboard.

**Comment by nhaugo** [comment]
@rkuchan can we put in the known issues that single-stat graphs with custom time ranges will return inconsistent results if there are multiple fields in the query.

The work around is to use dashTime or to only return a single field from the query for single stat graphs

**Comment by jaredscheib** [comment]
What is the current desired path forward with this, engineering-wise? We _could_ ensure order client-side, regardless of the order that the server sends data back in. Thoughts?

**Comment by goller** [comment]
@jaredscheib 
@cryptoquick and I looked at this briefly and it the query string is being reconstructed rather than using the correct field in the response.  

The response from the `/queries` endpoint has both `query` and `queryConfig` as a key.  Currently, the code is using `queryConfig` rather than `query`.

I think the way forward is for the app to use `query` as it is the query passed to the endpoint.

**Comment by jaredscheib** [comment]
Turns out the order was randomized by using `map` on the server-side, so we changed this to preserve order.
