### ISSUE TITLE
Redesign data explorer to work as a replacement for the admin console.

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1162]

**Comment by alexpaxton** [comment]
### Concept
- Only 1 query (instead of multiple on one graph)
- Add a DB dropdown instead of choosing from list
- Toggle between `Builder` and `Editor` mode
- Add `Query Templates` dropdown when in `Editor` mode, include Meta queries here
- Tags list will display all tags (from all measurements) until the user selects a measurement (More explorable)
- Measurements is no longer a list, would work like a autocomplete dropdown. If empty, clicking the dropdown will show a full list
- No resizer

#### Editor Mode
![de-redesign-builder-mode](https://cloud.githubusercontent.com/assets/2433762/24635546/c7710628-1888-11e7-8efe-c0ac7cfa70a6.png)

#### Builder Mode
![de-redesign-editor-mode](https://cloud.githubusercontent.com/assets/2433762/24635564/e7927572-1888-11e7-90a7-ec398efc5e54.png)

#### Compare the 2 modes:
![de-builder-editor-compare](https://cloud.githubusercontent.com/assets/2433762/24635574/f68a4faa-1888-11e7-98c5-917f272e8b80.gif)

#### Thoughts/Questions
- How do we let the user know that switching to Editor mode stops the "query builder" from affecting the query?
- Is this a non-issue
- How does this affect the design of Dashboard Editing
