### ISSUE TITLE
Server accepts queries containing `"count"` as a fieldname, but returns the query with quotes removed

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1193]
Talk to @lukevmorris or @jackzampolin if you'd like to connect to the data source.

Repro steps:
- Create a new dashboard
- Edit the default cell
- Remove the default query
- Add a new query: Type my own query
- Paste `SELECT moving_average(mean("count"),14) FROM "usage_computed"."autogen".unique_clusters_by_day WHERE time > now() - 90d AND product = 'influxdb' group by time(1d)`
- Should see data come back in the Overlay
- Save the cell

Result:
Query is submitted to server.
Server can parse the query.
Server returns it as `SELECT moving_average(mean(count),14) FROM ...`. Notice the missing quotes around `count`.
Client saves this new string, and asks for data via the influxdb proxy.
Proxy says "That's not a valid query"

**Comment by goller** [comment]
Looks like this bug comes from https://github.com/influxdata/influxdb/blob/master/influxql/parser.go#L2959 in the influxql parser.

Specifically here: https://github.com/influxdata/influxdb/blob/master/influxql/token.go#L75

The .ToString() function of an influxql statement doesn't list function names like `count` as reserved works that need to be double quoted.
