### ISSUE TITLE
Chronograf Support for Non-Admin User

### ISSUE THREAD

**Issue by danyli78** [influxdata/chronograf#1374]
When I add a non-admin user for an InfluxDB instance, I always get a "Unable to Connect to Source" error for all functions (host list, explorers etc...).  

Use Case: We want to give developer access to create alerts but do not want them to access the Admin functions of Chronograf.  Is it possible to eliminate this error, as this would be very annoying to the user.

**Comment by goller** [comment]
Hi @danyli78 , thanks for writing in.  The problem is that before Influx 1.3 non-admin users could not run `SHOW DATABASES`.  Without knowing what databases the user had access to we aren't able to show the hosts, explorers, etc.  However, with https://github.com/influxdata/influxdb/pull/7974 in the upcoming 1.3 release this problem will no longer be and your use case should be totally supported.

**Comment by nhaugo** [comment]
This will be addressed by features in InfluxDB 1.4

**Comment by waldenn** [comment]
Hi, is there a approximate timeframe when 1.4 wll be released with this fix? Thanks.
