### ISSUE TITLE
Publish 1.2beta to DockerHub

### ISSUE THREAD

**Issue by mcandre** [influxdata/chronograf#1394]
Please publish chronograf:1.2beta to DockerHub, so that container users can easily deploy this stuff!

In the meantime, are older versions of Chronograf like 1.0.0-rc1 or 0.13 compatible with v1.2 of the rest of the TICK stack?

**Comment by jackzampolin** [comment]
@mcandre We publish a public Docker image over on Quay:  `docker pull quay.io/influxdb/chronograf:latest`. 

The older versions of Chronograf were a substantially different piece of software and only integrated with InfluxDB. The Influx API hasn't changed since then, so it does still work with the newest bits. I've actually got an instance of it that I still manage and it works great with the 1.2 database.

**Comment by goller** [comment]
@mcandre ... although we'll be publishing chronograf 1.3 to docker hub when we release it!
