### ISSUE TITLE
administer telegraf agent

### ISSUE THREAD

**Issue by thaentzler** [influxdata/chronograf#1409]
[ Feature request ]
 Hello,

It could be really cool to add the capacity to administer the telegraf agents remotely from chronograf (config, maintenance, grouping).

I know it's an huge features to add. But it can be a really killer features :)

**Comment by goller** [comment]
Hey there @thaentzler thanks for writing in ! Awesome idea and it is totally going to be done.  

We are going to do work with telegraf to make it have an API to configure.  Chronograf would hook right into it.

**Comment by poulhs** [comment]
[Feature unrequest]

I certainly hope that this feature is going to be disabled by default (or even better: not implemented)!

As far as i am concerned, one should use configuration management tools for configuration, and telegraf/chronograf is _not_ that!

Allowing chronograf to configure telegraf through an API is wrong in so may ways:

* Nothing indicates that people/systems having access to chronograf also should be able to change configuration on a server (it may be different roles).
* Having an API on telegraf that enables two-way comminucation will require proper authentication (and that varies, e.g. two-factor authentication is common).
* And the authentication must be done by the telegraf, otherwise it would be too easy to get around.
* It could be possible to reconfigure telegraf to execute arbitrary commands or lie somehow.

A much better idea, if one absolutely wants to go down that path, is having a stand-alone process (with the API) for reconfiguring, then chronograf could interact with that and if one did not want this, it is much easier to disable (do not install the stand-alone program).

There are several such tools already, one is called puppet.

**Comment by goller** [comment]
@poulhs really good points!
