### ISSUE TITLE
[feature request] ability to see kapacitor logs for specific tasks

### ISSUE THREAD

**Issue by danyli78** [influxdata/chronograf#1467]
I can see it's very useful to have an interface where you can view custom Kapacitor scripts. Some of features i can see useful is:

- view custom scripts, even the entire output of "kapacitor show task_name" would be nice.
- ability to edit the scripts or var 
- ability to see logs from that specific tasks

**Comment by goller** [comment]
Hey @danyli78 , absolutely!

Here is the issue to track for custom scripts: https://github.com/influxdata/chronograf/issues/789

As for logs, it is on our roadmap to expose logs as an endpoint from kapacitor. Chronograf will show that data in the UI.  

So, because we have an editor issue already, do you mind if I change this issue's title to "ability to see kapacitor logs for specific tasks?"

**Comment by danyli78** [comment]
Yes go ahead and change the title. thanks!!! awesome work you guys.

**Comment by russorat** [comment]
added in https://github.com/influxdata/chronograf/issues/2073
