### ISSUE TITLE
As a user I can see a status page

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1556]
The status page should have:
- [ ] a bar graph each bar being the number of alerts triggered per day
- [ ] a list of alerts that triggered
- [ ] a list populated by an rss feed
- [ ] two or three graphs

**Comment by alexpaxton** [comment]
Use react grid layout for this page

**Comment by alexpaxton** [comment]
![status-page-v1](https://cloud.githubusercontent.com/assets/2433762/26692271/ee00da66-46b4-11e7-9340-26cd4648985e.jpg)

### Notes
- As mentioned above, use react grid layout
  - Trying to re-use as much as possible
  - Cells should use the existing headers from dashboards
  - Up for discussion: Should cells be resizable and/or draggable?
- **Bar Chart Cell**
  - 30 bars divided evenly across the graph (which is why it is full width)
  - TBD how to build the bar graph, might use an existing framework or just hack something together using canvas (math seems simpleish)
  - Gradient scales from `x = 0` to the maximum x value, that way the hot spots look hot
- **Newsfeed Cell**
  - Takes 1 or more RSS feeds
  - Format each post to be consistent
  - Will eventually have integration with support tickets (users can see updates on their tickets)
  - Needs a little more definition for the initial version of this
- **Getting Started Cell**
  - Links to Chronograf Docs
  - Should source content from a markdown file

**Comment by jaredscheib** [comment]
Should the bar graph refresh at a regular interval, like graphs in a dashboard?
And should these other cells refresh, or might they be subscribed to changes in real-time?
Should a user should able to change the timeRange of their bar graph? And the recent alerts?
Is there an existing RSS link, or where is that data coming from?

**Comment by jaredscheib** [comment]
Basic layout is in place: <img width="1440" alt="screen shot 2017-06-05 at 7 13 33 pm" src="https://cloud.githubusercontent.com/assets/6403018/26808539/189a0bf0-4a23-11e7-8a2d-70416bec8b13.png">

**Comment by jaredscheib** [comment]
My thinking so far is to not use Redux for this page, since we will likely want it to refresh frequently, and never show old data. There also isn't any editing in the spec thus far. The branch can be seen at https://github.com/influxdata/chronograf/tree/feature/status_page-1556.

**Comment by nhaugo** [comment]
- Should the bar graph refresh at a regular interval, like graphs in a dashboard?
Yes

- Should the other status cells refresh at a regular interval? Or might they subscribe in real-time, such as the Recent Alerts? Will some be static, such as the Guide?

Refresh

- Should a user should able to change the timeRange of their bar graph? And the recent alerts?

Not right now, it should be 30 days for now

- For Newsfeed, is there an existing RSS link, or where is that data coming from?

TBD I was thinking about using this https://jsonfeed.org/version/1

- Do we imagine more status cell types going forward?

Best to think of the cells as any graph and this is a dashboard with a default setup

- Will the user be able to Edit or otherwise modify the data (such as a cell query) in any of the cells?
Do we want to be able to view this page in Presentation Mode?

Yes, plan on an rss feed url as a command line option

- Will Recent Alerts be calculated by the client retrieving all alerts and then slicing, or do we want to write this logic (if it exists, I haven't found it so far) on the server?

Not sure I understand, the alerts should be scoped to the last 30 days, then if a bar is selected the selected day. Assume the user is on a given time frame and we will select the alerts for that time frame.

**Comment by nhaugo** [comment]
• For the list initial load should query alerts `time > now - 30d limit 30`
• At the bottom of the alerts list add a get more
• Scroll through results as the keep coming

**Comment by nhaugo** [comment]
@alexpaxton what does "Cells should use the existing headers from dashboards" mean

**Comment by nhaugo** [comment]
Add title bar controls for refresh and datasource

**Comment by alexpaxton** [comment]
@nhaugo same "title bar" markup and styles. Includes the context menu (little arrow on the right) in case we add options to a cell, also to ensure the names of cells appear consistent with graph cells

**Comment by jaredscheib** [comment]
And what do you want the `url` to be for this page, `/sources/{id}/status` or `/sources/{id}/dashboards/status`?

**Comment by jaredscheib** [comment]
Current status notes:
- A query for the last 30 days can take some few seconds to load, depending on one's internet connection. Currently I've got a Line Graph at the top of the screen, until a Bar Graph is ready.
- What do we want the Recent Alerts to display if there are no recent alerts? See the following:
<img width="1440" alt="screen shot 2017-06-08 at 2 48 29 am" src="https://user-images.githubusercontent.com/6403018/26917719-f8ba95ec-4bf4-11e7-8136-5f7e3b10ee22.png">
- Currently in the branch, I've taken a preliminary step toward "widgetizing" the `AlertsApp` container. It'd be great if @alexpaxton could take a look at this and see how we might use styles to accommodate accordingly, as you can see below it only gets us so far. I'm currently just using a simple conditional in the `AlertsApp` container to either render it as a `page` or not, but I would suggest that we may want to adopt a pattern of using a HOC called `FullPage` (or something to that effect) that takes what would otherwise default to a (possibly responsive) widget that fills whatever space it's in, without much borders/padding, and styles it for Full Page. This would be useful to replace a lot of the styles boilerplate that we have in most all of our containers and some possibly some components, and allow us to use the various pages as either smaller widgets or full pages throughout the app, and would preempt the need to use janky conditionals that require redundancy, as can be seen in what I'm currently doing.
<img width="1440" alt="screen shot 2017-06-08 at 2 49 25 am" src="https://user-images.githubusercontent.com/6403018/26917753-19f14102-4bf5-11e7-95ec-43456486aa04.png">

**Comment by jaredscheib** [comment]
Next steps for development:
- Add an optional `limit` param to `getAlerts`
- Allow more to be loaded (upon scroll ?)
- Newsfeed (JSON RSS)
  - sample resources: https://daringfireball.net/feeds/json, https://jsonfeed.org/version/1
- Markdown guide
- Review & possibly refactor how cells + LayoutRenderer are coordinating

**Comment by nhaugo** [comment]
I think this can be a special case for the url, seems confusing to smash it into dashboards

The query should be fast, it should be something like `SELECT sum("value") AS "sum_value" FROM "chronograf"."autogen"."alerts" WHERE time > now() - 720h GROUP BY time(1d)`

Recent alerts can say something like `there are no alerts please see getting started on how to set them up` I will get better verbiage in the future but that should work for now

**Comment by jaredscheib** [comment]
And @goller, for the news feed, do you imagine that we might add a proxy `/status`, or possibly `/status/jsonfeed` API endpoint that gives a JSON feed response object?

**Comment by jaredscheib** [comment]
Current status:
- Alerts widget has been styled (thanks @alexpaxton!)
- Basic JSON NewsFeed has been implemented:
  - `<NewsFeed>` + `<JSONFeedReader>` are displaying local fixture data (from https://daringfireball.net/feeds/json)
- Added next steps in above checklist

Here's what it's looking like: 
<img width="1440" alt="screen shot 2017-06-09 at 1 50 31 am" src="https://user-images.githubusercontent.com/6403018/26964210-185b20c6-4cb6-11e7-8497-842f9ed30795.png">

**Comment by alexpaxton** [comment]
Current Status:

- Made the `Recent Alerts` cell a bit larger as to avoid table crunch
- Changed design of newsfeed a little
  - Slightly more compact
- Fleshed out `Getting Started` with static content
  - Initially figured using a markdown parser would be good
  - Realized we might not be changing this content very often
  - Static content = 99% of the way there, now

![screen shot 2017-06-09 at 4 51 29 pm](https://user-images.githubusercontent.com/2433762/26998084-69a65396-4d34-11e7-9303-64a3368de88a.png)

**Comment by jaredscheib** [comment]
Remaining steps for consideration have been added to the PR WIP Notes at #1608
