### ISSUE TITLE
Allow users access to Chronograf if they haven't configured an oauth provider

### ISSUE THREAD

**Issue by lukevmorris** [influxdata/chronograf#1694]
After running `chronograf` without providing any oauth configuration via environment variables or command line options, I expect to be able to access my Chronograf instance without having to authorize. Instead, I'm redirected to the login screen and asked to Login with Auth0.

If I click that button, it tries to direct me to `https://authorize/?access_type= ...`

The server logs are spitting out `Invalid principal` when attempting to access `/chronograf/v1/me`

**Comment by jaredscheib** [comment]
This is because your AUTH0 env vars are set, so it's expecting to try to log in. Try unsetting them, and see if it allows you to use Chronograf.

Also a partial dupe of https://github.com/influxdata/chronograf/issues/1666, I think.

**Comment by jademcgough** [comment]
I had a similar problem when I was testing authentication (not specifically auth0), where after using authentication I had a hard time disabling authentication (I ended up commenting out the server code that handled authentication).

**Comment by lukevmorris** [comment]
@jaredscheib @timraymond @jademcgough @nhaugo so sorry. Looks like I had some `AUTH0` stuff set from another project. `unset`ing those values allows me to access Chronograf without having to authenticate.

**Comment by danlg** [comment]
@lukevmorris @timraymond 
I'm having this exact issue where the splah screen  prompts "login with Auth0" but when clickinon it it redirects to
`https://authorize/?access_type=online&client_id=..`

I find https://authorize URL bizarre. When I roll over the button, the link is "http://swarm-dev-external-xxxx.eu-west-2.elb.amazonaws.com:8888/oauth/auth0/login" which looks correct.

I want to enable auth0 authentication, not disable it so the previous solutions will not work. The Auth0 is correctly set up.

the code to run it is:
```
docker service create --name chrono  \
    --detach=false \
    -e "INFLUXDB_URL=https://mydb:8086" \
    -e "INFLUXDB_USERNAME=xxx" \
    -e "INFLUXDB_PASSWORD=xxx" \
    -e "AUTH0_DOMAIN=xxx.eu.auth0.com" \
    -e "AUTH0_CLIENT_ID=clientid" \
    -e "AUTH0_CLIENT_SECRET=secret" \
    -e "PUBLIC_URL=http://swarm-dev-external-xxxx.eu-west-2.elb.amazonaws.com:8888" \
    -e "PORT=8888" \
    -p 8888:8888 chronograf:latest
```
Please reopen the issue ;-)
Any ideas on solving it ? Tx

**Comment by goodwink** [comment]
I am having the same problem as @danlg exactly.  After reviewing the chronograf source I became suspicious that we were specifying AUTH0_DOMAIN in the wrong format.  I confirmed this using Go Playground and determined that it should be specified with a scheme, i.e. "https://xxx.eu.auth0.com" in your example.  After changing this it gets past the previous issue, but then it fails for me with an auth0 error indicating that the callback URL is wrong.  In my case the callback URL is coming through as the path only, not the scheme or host.  At the very lease the format of this env variable should be documented as it is not intuitive at all to need to include a scheme on something called a "host", this would be a URL/URI rather than a host format.  Better yet, the code should be changed to accept the intuitive value (and the format should still be documented).  I am now working through the remaining issues with auth0, but it seems that either the documentation is incomplete or this authentication method's tests are not representative of the actual integration.

**Comment by goodwink** [comment]
It turns out that PUBLIC_URL is required and this is documented in the documentation of the parameter itself in the configuration section that it is used for auth0, but on the OAuth configuration documentation page it isn't mentioned for auth0 and it should be.  It is mentioned, for example, in the google OAuth configuration documentation.
