### ISSUE TITLE
Function field toggle button alignment slightly off

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#1706]
<img width="596" alt="screen shot 2017-07-07 at 4 04 05 pm" src="https://user-images.githubusercontent.com/6403018/27980050-8ff67902-632f-11e7-92cb-6d18988ea658.png">

Connect #1692

**Comment by AbleLincoln** [comment]
Looks like this is due to this [piece of code](https://github.com/influxdata/chronograf/blob/master/ui/src/style/components/fancy-scrollbars.scss#L58-L61) that's been marked with "Hacky fix to hide strange white lines in chrome". I guess we could offset this weird negative margin with some positive padding? Unless there is a better way to solve the chrome lines issue, then we could get rid of the hacky fix all together.

**Comment by alexpaxton** [comment]
@jaredscheib I think this might be related to `FancyScrollbars` as occasionally they render strangely
