### ISSUE TITLE
Feature request: make start page configurable

### ISSUE THREAD

**Issue by core-process** [influxdata/chronograf#1790]
We use InfluxDB and Chronograf to collect and display various data from water filtering systems all over the country. Therefore we do not use Telegraf and the "Host List" is not used by us.

We would like to show either the "List of Dashboards" or a specific Dashboard as start page.

Is this feature part of the roadmap already? :-)

**Comment by nhaugo** [comment]
Hi @core-process, that is an interesting idea. Right now the focus is to make the status page more compelling (introduced in 1.3.3.0 as the new starting page) and to make the "host list" configurable to tags, i.e. instead of hostnames allow the list to be populated by any tag and the columns configurable.

**Comment by jaredscheib** [comment]
Hi @core-process, thanks for writing in. Very compelling suggestion indeed.

We're interested to understand your IoT use case more, as we want to make Chronograf more useful in that direction. Might you be willing to have a brief 30-min chat with us so that we can learn more about how you're using Chronograf, your use case, your perspective, etc.? If so, could you email me at jared@influxdb.com?

Thanks again!

**Comment by core-process** [comment]
:-(
