### ISSUE TITLE
Design doc for multitenancy

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1827]

**Comment by jaredscheib** [comment]
WIP
Client

Server
- [ ] Design a schema for a user
  - `id`: authMethod:authProvider:org:team:username (exception: Heroku doesn't allow org vs team)
  - `role`: slice of role pointers
- [ ] Design a schema for a role
- [ ] Create a user bucket in Bolt
- [ ] Create a role bucket in Bolt

**Comment by jaredscheib** [comment]
Here is an overview of our proposal and task list for the server side of the MVP for multi-user. @timraymond will be adding some prose here shortly to provide more context.

- [ ] Design a schema for a user
  - (has many roles)
  - `id`: authMethod:authProvider:org:team:username (exception: Heroku doesn't allow org vs team)
  - `role`: slice of role pointers
  - `default_source`: pointer to a the default source object in Bolt
  - `settings`: (time ranges, ui choices, etc.) -- flesh this out
- [ ] Design a schema for a role
  - (has many permissions)
  - does _NOT_ contain default source since these are composable
- [ ] Design a schema for a permission
  - (has one resource)
- [ ] Design a schema for a resource
- [ ] Create a user bucket in Bolt
- [ ] Create a role bucket in Bolt
- [ ] Create a permissions bucket in Bolt
- [ ] Create a resource bucket in Bolt (TBD)
- [ ] Add authorization wrapper for mux
  - [ ] Restrict access based on user’s role
  - [ ] Inject capabilities object into each top-level route response within the app
- [ ] Move default source to user
  - [ ] Refactor default source server flag for this when auth is in use
- [ ] Create new user upon new auth login
  - [ ] require id, role, and default source
  - [ ] defaults to superuser
- [ ] Create server flag for user default role
- [ ] Create API for superuser/admin controls
  - [ ] see a list of users, with assigned roles
  - [ ] see a list of possible roles
  - [ ] update a user’s role
  - [ ] see a map of permissions-to-resources, per role
    - we can hardcode the ones that they can’t change for now
- [ ] Not MVP
  - [ ] Update permissions on a role
  - [ ] Creating a new role
