### ISSUE TITLE
As a user I can see alert rules as scoped by my Chronograf Organization

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#1912]
This is only scoped to the kapacitor alert rule ui object, this has no effect on the user manipulating kapacitor through the kapa api, or tick script editor.

**Comment by nhaugo** [comment]
This doesn't work, but I don't understand how it possibly could given the same kapacitor instance on two different data sources.

**Comment by jaredscheib** [comment]
Looks like we accidentally included it on that PR. We haven't done anything on alert rules. Is it still a requirement? In addition to your reason, my understanding was that, since alerts/tasks are not Chronograf resources, we aren't going to try to manage them or scope them by organization. There was some discussion with @timhallinflux about tagging alerts by organization and thus being able to filter them on the Chronograf side, but disallowing access or otherwise scoping them as Chronograf resources might not make sense. Thoughts?

**Comment by nhaugo** [comment]
I'm closing this as there is no current use case
