### ISSUE TITLE
As a user I can see a permanent legend per cell

### ISSUE THREAD

**Issue by e-dard** [influxdata/chronograf#1981]
One thing that would a nice to have is the ability to visualise a set of series in unison, but then be able to focus on single series.

For example, in the following Grafana graph there are multiple series.

<img width="903" alt="screen shot 2017-09-08 at 11 41 53" src="https://user-images.githubusercontent.com/501993/30208300-bab0e7f4-948a-11e7-95d9-677dc87043fe.png">

At its most basic, the query to produce the above looks something like:

```
SELECT mean("memBytes") FROM "monitor"."tsm1_cache" GROUP BY "id" fill(null)
```

For each different `"id"` tag, Grafana adds a label to the legend. The really nice thing, though, is that when you click on one of the labels, the graph shows only that data, e.g., clicking on `15`:

<img width="890" alt="screen shot 2017-09-08 at 11 45 45" src="https://user-images.githubusercontent.com/501993/30208423-43af073e-948b-11e7-86e1-f50c694c07c6.png">

 1. It would be great if we could do something similar in Chronograf.
 2. It would be even cooler if we could have something "up top" where template variables are, that would allow us to select tag values that would then be applied _to each cell in a dashboard_. 

To clarify (2), imagine if you had a dashboard that showed cpu, memory, disk space, load and network traffic for all your hosts. By default, each cell shows say 15 different series for 15 different hosts. It would be great if you could select host `us-west-abc1` and all the cells in the dashboard would filter out all the other series where `host != us-west-abc1`.

**Comment by nhaugo** [comment]
w/value is a nice to have, but should be a settable option

**Comment by ebb-tide** [comment]
@nhaugo @russorat 
- [ ] Should persistent legend visibility be settable on a per dashboard or per cell basis ? 
- [ ] Should the ability to toggle a series visible/invisible be only on the persistent legend, or on  the hovering legend as well? 
- [ ] Does this story include any other changes to the hovering legend? (should we display a more pared down version of the hovering legend to not repeat info?)

**Comment by russorat** [comment]
-  Should persistent legend visibility be settable on a per dashboard or per cell basis ?
   - Per cell
-  Should the ability to toggle a series visible/invisible be only on the persistent legend, or on the hovering legend as well?
   - since our hovering legend has other buttons that are clickable, this should work the same in both.  filed #2723 for that.
-  Does this story include any other changes to the hovering legend? (should we display a more pared down version of the hovering legend to not repeat info?)
   - IMO, we should keep this story focused on the static legend. If there are issues with the hovering legend, those should be filed and address in separate issues.

The behavior of clicking should be as follows: 
 - click on an individual series, only that series should be selected.
 - click again on the same series, all series should be selected.
 - holding shift or command while clicking a series should toggle that series. if user removes all series from the graph, it will be empty.

**Comment by ebb-tide** [comment]
@russorat what should default persistent legend visibility be?

**Comment by ebb-tide** [comment]
@russorat's (previous) responses: 

- Should persistent legend visibility be settable on a per dashboard or per cell basis ?  Per cell

- Should the ability to toggle a series visible/invisible be only on the persistent legend, or on the hovering legend as well?
since our hovering legend has other buttons that are clickable, this should work the same in both. filed #2723 for that.

- Does this story include any other changes to the hovering legend? (should we display a more pared down version of the hovering legend to not repeat info?)
IMO, we should keep this story focused on the static legend. If there are issues with the hovering legend, those should be filed and address in separate issues.

The behavior of clicking should be as follows:

- click on an individual series, only that series should be selected.
- click again on the same series, all series should be selected.
- holding shift or command while clicking a series should toggle that series. if user removes all series from the graph, it will be empty.

**Comment by russorat** [comment]
@ebb-tide default should be off.

**Comment by nhaugo** [comment]
Couple of things, the legend on/off status should be persisted so if i leave and return to a dashboard the legend will be in the state it was left.

@russorat My thoughts are when a second series is clicked it should be displayed along with an existing series that are displayed. When all series are toggled to off then all series should be displayed. Thoughts?

**Comment by nhaugo** [comment]
If there are lots of series we need to come up with a way to display all of them while still showing the graph. Can we figure out a minimum size for the graph, then if we exceed that space with tags we put them on a scrollable panel?
@alexpaxton

**Comment by alexpaxton** [comment]
Talked to @goller we're going to add a field to `cell` on the backend called `legend` that will be roughly this shape:

```
{
   "legend": {
    ┆   ┆ "type": "static_tags",
    ┆   ┆ "orient": "bottom",
    ┆   ┆ "other": "options if you need"
    }
}
```

Moved the toggle into visualization options and have most of the front-end anticipating the aforementioned shape

**Comment by ebb-tide** [comment]
TODO: 
- [ ] fix delay on rendering static legend. 
- [ ] fix click behavior in cell overlay.

**Comment by russorat** [comment]
- [ ] static legend should update as quickly as the lines on the graph

![legend_delay_2](https://user-images.githubusercontent.com/4805997/36758003-e2799546-1bc7-11e8-893c-0e5c43e84dcb.gif)

**Comment by russorat** [comment]
awesome! 🌈
