### ISSUE TITLE
Configure Alert Points is amazing and impossible to find.  

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#2013]
The only way to arrive at the amazingly simple way to set up slack alerts(for example) in kapacitor, is currently through Configuration-> Active Kapacitor Dropdown -> edit button -> Configure Alert Endpoints

If the Configure Alert Endpoints page were reachable through the alert rules set up page, it would seriously reduce the time to awesome. Suggestion: 

![screen shot 2017-09-19 at 3 30 11 pm](https://user-images.githubusercontent.com/10937678/30618732-8e4a602c-9d50-11e7-9f7b-71853ecb820d.png)

**Comment by jaredscheib** [comment]
I think this is a great idea in general. Some further ideas:

1. I'd suggest that this endpoint panel should simply show you all of the possible endpoints upfront, not just the ones you've configured.
1. Then, for any that you haven't configured, you can configure them inline right here. Maybe like a preliminary blue button for "Add Configuration" like we have for "Add Graph", etc., which is replaced by the inline configuration panel.
  1. And then, as a follow-on, place a Gear icon somewhere that allows the user to easily and accessibly re-configure a particular endpoint, inline.
1. We could use the design pattern for multiple queries on a graph to add multiple alerts per endpoint, or just add them to a list panel on the left.
1. In the list view above, we could show by color which ones are enabled, and sort the enabled ones to the top.
1. You could also allow for naming of individual endpoint alerts so that they aren't just all called Slack 1, Slack 2, Slack 3, etc.

**Comment by alexpaxton** [comment]
Tackling alongside #1610
