### ISSUE TITLE
how can i drop measuremet via chronograf?

### ISSUE THREAD

**Issue by zengbiao** [influxdata/chronograf#2022]
I got "**database not found**" when "DROP MEASUREMENT "dbname.measurememtname;""

**Comment by zengbiao** [comment]
any comments?

**Comment by nhaugo** [comment]
Looks like this is a bug.

**Comment by nhaugo** [comment]
Add support for DROP measurement, series, rp, and shard

**Comment by nhaugo** [comment]
Todo ask core what is the proper syntax for this query

**Comment by zhang8473** [comment]
still have this problem? I tested the recent build. Still the same problem

**Comment by bedrin** [comment]
Related to https://github.com/influxdata/influxdb/issues/8927

**Comment by turboslon** [comment]
Is there any workaround available?

**Comment by russorat** [comment]
@turboslon the reason this isn't supported in chronograf is because in order to drop a measurement, you first need a execute a `use db` command. the drop measurement query doesn't support the syntax `DROP MEASUREMENT "db"."rp"."measurement"` syntax from what i can tell based on my CLI and this issue: https://github.com/influxdata/influxdb/issues/8927

for now, there isn't much we can do on the chronograf side to support this in the UI.

**Comment by kwesolowski** [comment]
And its still impossible?

**Comment by russorat** [comment]
@kwesolowski it's still not possible via chronograf.

**Comment by bernardolm** [comment]
+1

**Comment by oh-jose-vazquez** [comment]
+1

**Comment by jslmariano** [comment]
Hi everyone do you think this should be reopen?

**Comment by russorat** [comment]
This PR https://github.com/influxdata/chronograf/pull/5652 adds this ability and will be included in the next release of Chronograf. Thank you!

**Comment by PaulCorbeau** [comment]
> This PR #5652 adds this ability and will be included in the next release of Chronograf. Thank you!

This is a good news, required :)
