### ISSUE TITLE
"Add Cell" Button on the dashboard page uses a "+" where other "add" buttons do not

### ISSUE THREAD

**Issue by ChrisChurilo** [influxdata/chronograf#2026]
The screen shows that the "Add Cell" button on the dashboard page in Chronograf has a "+" while the "Add Graph" button does not. I don't have a preference whether there should be a "+" or not - they should all be consistent.

<img width="496" alt="screen shot 2017-09-26 at 1 49 14 pm" src="https://user-images.githubusercontent.com/22224436/30883602-844c5b72-a2c1-11e7-821d-876b832bc0c2.png">

**Comment by jaredscheib** [comment]
Great point @ChrisChurilo – I think there are a couple of other places in the app that would benefit from this consistency as well, such as the tabs for Data Explorer and the in-flight feature of Rule Builder endpoints.

**Comment by nhaugo** [comment]
In this case the button with a "+" adds a widget where as the "add graph" button does not add a new widget. I could go either way @alexpaxton thoughts?

**Comment by alexpaxton** [comment]
I just looked through all the Add/Create buttons in the whole UI, and the `+` icon is apparently the oddity. Thinking back to when the `+` was added to the button it was because all the other buttons in the Dash page header have icons and it felt inconsistent to not have one. There are other inconsistencies such as the DE `+` not having a text label (seems obvious enough without it).

I'll take another pass through the UI tomorrow and try out some different approaches, see what feels best.
