### ISSUE TITLE
As a new user, it's unclear that placeholder text is not actually prefilled text

### ISSUE THREAD

**Issue by melinamurray** [influxdata/chronograf#2032]
I didn't realized I needed to type in information, but thought the placeholder text was all that was needed. (E.g. Manage Sources and Alert Rule endpoint parameters)
<img width="922" alt="screen shot 2017-09-26 at 3 21 52 pm" src="https://user-images.githubusercontent.com/32313305/30887019-74b6a7c8-a2ce-11e7-8b08-e5561cdf5490.png">

**Comment by jaredscheib** [comment]
Great to know. Thanks, @melinamurray!

**Comment by nhaugo** [comment]
@alexpaxton thoughts?

**Comment by alexpaxton** [comment]
I believe we had an almost identical issue on the Kapacitor config page, and the solution we came up with can work here as well:

![screen shot 2017-09-28 at 8 25 05 pm](https://user-images.githubusercontent.com/2433762/30999642-34f883ae-a48b-11e7-8455-63c70413bc73.png)

Instead of having the example connection string and name as placeholders, we set the fields to be pre-filled. If the user changes anything and wants to revert back they click `Reset` (which might need to be renamed "Reset to Defaults")

**Comment by jaredscheib** [comment]
That sounds like a reasonable solution me. Additionally, what if we made the placeholder text italicized throughout the app? Or some other style effect that would clearly not be the same as text that one might input. In other words, I think the lack of clarity comes from using only grayscale color as the differentiator, whereas some other more stark stylistic difference could make this generally clearer throughout the app.
