### ISSUE TITLE
Logout user if their current organization is no longer valid

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2379]
I removed a user from an organization, and yet when they refresh, it says in Purgatory that they are currently signed into that organization. We should clear their current organization when they are removed from any organization, or at least if it's the one they were currently signed in.

**Comment by desa** [comment]
when they go through authorization and we see that they are not in their current org, clear the org and send back unauthorized.

**Comment by desa** [comment]
https://github.com/influxdata/chronograf/pull/2399

**Comment by desa** [comment]
Just looked through this code. It would require a refactor to achieve this kind of functionality. And the refactor would open up another place that can modify the JWT.

Currently, the only two pieces that can modify the JWT are `PUT /me` and the OAuth flow. To do this, I'd have to expose the JWT modifying logic to the `AuthorizedUser` function. Which runs on every request. I'd like to be a bit cautious about exposing otherwise incapsulated pieces of the code.  

If the UX is too confusing, we can add it.

It may be able to bypass this issue by making a request to `/me` before sending someone to purgatory.

**Comment by desa** [comment]
What about if your current organization is deleted, we make you do an auth flow again?

**Comment by jaredscheib** [comment]
Let's just have them re-authenticate for now if that's easier.
