### ISSUE TITLE
Add threshold values with colors to single stat

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2391]

**Comment by alexpaxton** [comment]
![screen shot 2017-12-08 at 6 22 16 pm](https://user-images.githubusercontent.com/2433762/33791707-14b505e4-dc45-11e7-9ac9-cb75c2b37f9c.png)
![screen shot 2017-12-08 at 6 22 38 pm](https://user-images.githubusercontent.com/2433762/33791708-17ddbd74-dc45-11e7-9731-671020ae2b30.png)
![single-stat-to-gauge](https://user-images.githubusercontent.com/2433762/33791710-1a41f13e-dc45-11e7-87cd-798e4056791c.gif)

### Progress Update
- Refactored some of the gauge code so that both types can use the same shape without changes to the back end
- Previously each item in `colors` had a `type` key that was either `min`, `max`, or `threshold`. Moved away from this typing system as I realized I can deliver the same UX without it and share a lot of UI with single stat customization
- Since `gauge` and `single-stat` now use the same data switching cell types reflects this in the UI
- `single-stat` can have 0 items in `colors` whereas `gauge` requires at least 2
- Switching from a `single-stat` with less than 2 colors to `single-stat` sets reasonable defaults
- Moved the `+ Add Threshold` button to the top of the list
- Gauge now handles negative values smoothly
- The Gauge needle won't rotate off the visible gauge

### To-Do
- Need to write some logic that determines a legible text color for the brighter colored backgrounds
