### ISSUE TITLE
No QUERY builder in kapacitor alert rule wizard

### ISSUE THREAD

**Issue by hydro-b** [influxdata/chronograf#2405]
In the documentation for building kapacitor alert rules: https://docs.influxdata.com/chronograf/v1.3/guides/create-a-kapacitor-alert/, there is the possibility to "build a query". In the chronograf / kapacitor we have, 1.3.10.0-1 / 1.3.3-1 resp. there is no such field. So it's not possible for us to build the QUERY we want. See a screenshot from our chronograf below:
![chronograf_alert_rule_buider](https://user-images.githubusercontent.com/6695474/33132804-f01095d4-cf9a-11e7-9fc4-b06b8312b775.png)

**Comment by jaredscheib** [comment]
Thanks for writing in, @hydro-b. We removed the query builder for Kapacitor alerts recently because the rules that Chronograf builds are actually streams, and building a query is a batch alert concepts. This is a good note for updating our documentation (cc @stevebang). If/when we support batch-based alerts in the future in Chronograf, we'll likely add a query builder back in for that.

**Comment by russorat** [comment]
This issue was moved to influxdata/docs.influxdata.com#1416
