### ISSUE TITLE
Add basic alerts queue page for ops work management

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#2501]
An ops team that is responsible for responding to alerts may find value in an alerts management page, i.e. a work queue manager. There, they can mark a status (e.g. `Completed`, `Ignore`, `Confirmed`, etc.) and use this page to manage their work in responding to alerts. This functionality exists in other systems, such as in Apache Arrow:
![img_1695 cropped](https://user-images.githubusercontent.com/6403018/33692066-60d2697c-daa0-11e7-9d6f-f78d1594be8e.jpeg)

Nothing is necessarily needed in Kapacitor to implement this currently in Chronograf.

cc @nathanielc

**Comment by nathanielc** [comment]
> Nothing is necessarily needed in Kapacitor to implement this currently in Chronograf.

Let me clarify, Kapacitor provides features to generate alerts and to see the status those alerts, nothing more. This means that Chronograf will need to track the alert history (which it already does). And provide a way to interact with the alerts i.e. setting the status to Completed, Ignore, Confirmed etc.

>  This functionality exists in other systems, such as in Apache Arrow:

Apache Arrow is not an alerting system, its a serialization specification. There are many alerting systems out there see https://docs.influxdata.com/kapacitor/v1.3/nodes/alert_node/ for a list of systems Kapacitor can already integrate with. Most of these systems do this and more already.

**Comment by jaredscheib** [comment]
Thanks @nathanielc. Super helpful.

And btw I wrote Apache Arrow but meant Airflow, vis-a-vis the image above.

**Comment by goller** [comment]
@nathanielc to add a bit more color to this... if I remember correctly, you've been hesitant to add full alert management to kapacitor and hoped kapacitor clients would handle this, no?

Also, @jaredscheib there could be some way of chronograf "silencing" alerts, but, many people use the external providers (pagerduty, victorops) to be the dashboard of alerts/on-call schedules/etc.

I personally think that chronograf should reflect the current state of the alerts rather than add all the features of a full alert management platform.  However, perhaps there is some design middle ground.
