### ISSUE TITLE
Proposal: increase auto-refresh interval options

### ISSUE THREAD

**Issue by tartragon** [influxdata/chronograf#2514]
Hello everyone,

Ref. #781 and #957

The auto refresh intervals already defined (dashboard and individual graphs) cover only a limited number of use cases. The lack of "1 second" refresh interval is, for example, a big limitation when we talk about monitoring a system.

It would be interesting to have a wider range of options to choose from (starting with the "1 second" option), or even better, to allow the user to configure those intervals.

Many thanks!

**Comment by goller** [comment]
@tartragon thanks for writing in! We totally should have arbitrary intervals here.

In the distant future I'd like the chronograf server to handle running those queries and stream results real-time to the webapp... that's a bit away though :)

**Comment by tjohnston-cd** [comment]
I'm interested in the same thing, but for the relative time windows viewed:
![reltime](https://user-images.githubusercontent.com/42251505/46698682-b9cd7800-cbe5-11e8-84cf-9c44282db08f.png)

I noticed `?lower=now() - 6h` at the end of my dashboard URL. If I set this to `?lower=now() - 2h`, the page loads with the 6 hour window set and an error: `Invalid URL query value supplied for lower of upper time range`

Is it possible to do what I want, but I've just missed it? 

If not, it would be great to have support for this added.

**Comment by JamieCorkhill** [comment]
Is there any plan to decrease the refresh time to a ~1-second interval?

Additionally, and please forgive me if this is a stupid question for today is my first time having used the TICK Stack, but is there any way to use Chronograf as a dashboard for sensor data from a Raspberry Pi/Arduino/Particle rather than through InfluxDB? If it's done that way, could I have Chronograf retrieve data via an open socket rather than polling every 5 seconds from the database?

So, my desired architecture would be to have my hardware (Arduino/Pi/National Instruments/Particle/Etc.) send data via an open socket to Chronograf for real-time (and I mean real-time not 5 seconds) visualization, and also to InfluxDB. That would permit me to use Chronograf to both display data as it comes in and to analyze InfluxDB at a later time.

Is that at all possible?

Thank you.

**Comment by Gelob** [comment]
This should be re-opened!

**Comment by JamieCorkhill** [comment]
Indeed it should. The refresh rate will be a determining factor in whether I use Chronograf or build my own solution.

**Comment by let4be** [comment]
Is there any update? I need sub second update interval, how do I do it?...
