### ISSUE TITLE
it should be "session timed out, please log in again" instead of login

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2519]
![image](https://user-images.githubusercontent.com/4805997/33780336-42610b68-dc05-11e7-9a60-e0c2ef57290f.png)

**Comment by jaredscheib** [comment]
http://www.dictionary.com/browse/login – it's apparently a verb in the current spelling, according to the dictionary.

If we want to make this change, it's a broader copy issue and should include all button copy, and anywhere else that `login` is used.

**Comment by russorat** [comment]
@stevebang what's your take?

**Comment by stevebang** [comment]
I think we resolved this a few days ago verbally:

log in: verb
login: noun or adjective

As for the message, changing it to this would make it more friendly:

"Your session has timed out. Log in again to continue." [followed by login page?]

**Comment by jaredscheib** [comment]
@russorat Resolving this issue created inconsistency with the usage of `login`, which existed as button copy in two other parts of the app: Purgatory.js and Login.js. I fixed this, but in the future let's be sure to cover all cases of this kind of thing so that @nhaugo doesn't introduce more bugs [sic] like this one into the codebase 😉
