### ISSUE TITLE
As a super admin member in the default organization, when I delete a user in the default organization, and they have a role in another organization, they only get deleted temporarily

### ISSUE THREAD

**Issue by kevinhogan111** [influxdata/chronograf#2524]
STR:
1) In the default organization from sources/1/admin-chronograf attempt to delete an admin user.
2) Note a dialogue box is thrown in the UI saying, "user removed from Oath:google:"users email", also note at this step that the user's email address is no longer visible on the page sources/1/admin-chronograf.
3) Refresh the page.
4) Now click the "Users" button to go back to the user view.

-expected result: The user you just deleted is not visible.

-actual result: The user you just deleted is visible.

**Comment by jaredscheib** [comment]
We were able to reproduce this (on the same instance) with the following conditions:
1. Public was off;
1. User B was a member of two organizations;
1. User B was not a SuperAdmin;
1. User B was signed into a non-Default organization;
1. User A deleted User B from the Default Organization;
1. User B was not logged out, as expected since they were signed into a different org, but they were given the Default Role in the Default Org (we confirmed this by doing the steps above and having Default have a Default Role of `Editor` and `Admin`);

**Comment by jaredscheib** [comment]
In exploring with @desa, we discovered that it turns out that this is on purpose, because we made it so that users of the application had to have a role in the Default organization if they had a role in _any_ organization. This was a vestige of an early approach to having a global user list: https://github.com/influxdata/chronograf/commit/3ddd253d6.

We decided that this should be reverted, and if we want a global user list in the future, it should be under a special API for SuperAdmins only. But for now, a user should be able to have a role in a non-Default organization, and no role in the Default organization.
