### ISSUE TITLE
As a User I can configure Single-Stat visualizations to change text color instead of the entire background

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/chronograf#2548]
For those who want the color changing effect but less retina burn

Would need a `boolean` option on `colors` - @goller thoughts?

**Comment by goller** [comment]
@alexpaxton I'm not a fan of boolean options, but, a more descriptive API.  Is the central tension in the API that the cell has one `colors` parameter that currently doesn't state what data the colors represent?

For example, the `colors` make sense with the gauge because the data is encoded into a single set of colors.

However, with single-stat the color could represent the background fill or the text fill.

 Taking ideas from the wonderful vega project: https://vega.github.io/vega-lite/docs/scale.html#scheme

... I'm thinking we need to specify what the data is encoded into the color with a new parameter.  vega uses `field`.  

So, for single-stat a color could look like this:

```json
[
{
    "id": "1234",
    "type": "min",
    "hex": "0x000000",
    "name": "black hole",
    "value": "10.0",
    "field": "area",
},
{
    "id": "1234",
    "type": "min",
    "hex": "0xFFFFFF",
    "name": "supernova",
    "value": "10.0",
    "field": "text",
}
]
```
... corresponding to white text on a black area when the value is 10.0.  

The various values of the `field` informs how the data should be encoded into color.

Ok, so, in vega the word `field` represents the lookup key into another object.  I like this because the front-end can define which fields make sense for the internal representation of the graphics.

**Comment by russorat** [comment]
issues found in acceptance testing:
 - [ ] default behavior should match the behavior in previous versions
 - [ ] Behavior with a single threshold is strange. A single threshold should always be the same color and should show up with a threshold of 100.
 - [ ] Auto-Refreshing the single stat seems to reset the colors when editing
 - [ ] Auto-Refreshing sometimes makes the single stat completely disappear

![kapture 2018-01-31 at 17 58 43](https://user-images.githubusercontent.com/4805997/35657267-78d4a260-06b0-11e8-963b-cc8250bde326.gif)
![kapture 2018-01-31 at 17 53 08](https://user-images.githubusercontent.com/4805997/35657268-78f02bde-06b0-11e8-94f8-8a5a7e7c2161.gif)

**Comment by alexpaxton** [comment]
Completed the first two items, and also fixed a weird bug I found in which single stat + line graph was wrecked

Going to look into the auto-refreshing bit tomorrow AM

**Comment by russorat** [comment]
LGTM!
