### ISSUE TITLE
Admins cannot create new users

### ISSUE THREAD

**Issue by desa** [influxdata/chronograf#2583]
From https://github.com/influxdata/chronograf/issues/2214#issuecomment-351831902
> When an Admin tries to create a user with superAdmin: true, they now get a 500 (Internal Server Error): Cannot find configuration error response from the server. It should fail, but I would expect a 401 Unauthorized, or something a bit more specific. Not sure if this will become possible once the noop refactor is done.

When we introduced https://github.com/influxdata/chronograf/pull/2552 I failed to realize that this would actually prevent admin users from being able to create new users.

**Comment by nhaugo** [comment]
When logged into an org as an admin, but not as a super admin, i see the users screen with a create user button. Clicking the button does nothing, additionally I cannot see any users.

**Comment by jaredscheib** [comment]
I'm not seeing this bug, @nhaugo. This might be related to https://github.com/influxdata/chronograf/issues/2573 – what happens when you refresh your browser?

**Comment by desa** [comment]
@jaredscheib I think this is an admin trying to create a super admin. Which, even if super admin new users is true, isn't possible.

**Comment by nhaugo** [comment]
@jaredscheib no error message, just the behavior i desecribed

**Comment by nhaugo** [comment]
![screen shot 2017-12-15 at 3 04 48 pm](https://user-images.githubusercontent.com/1003269/34063800-617e8d00-e1a9-11e7-8d3f-3f561d1becd1.png)

**Comment by jaredscheib** [comment]
This second issue is due to `users` being stale after switching organizations. This can really only reasonably be solved by the same work required by https://github.com/influxdata/chronograf/issues/2573. There needs to be a UsersPage, just like there's an OrganizationsPage, and that container should load Users fresh every time it mounts. `name` is not found by in the search for `currentRole` because `users.roles` is based on the users from a previous organization.
