### ISSUE TITLE
Switching public off doesn't seem to do anything

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2596]
I turned off public for default and was still able to log in with an account that was not added

**Comment by desa** [comment]
Just tried to repro this myself and everything seemed to be working as expected to me.

**Comment by desa** [comment]
I think I know what the issue may be for both this issue and https://github.com/influxdata/chronograf/issues/2597

They're both expected behavior, but super unintuitive.

When a user is removed from an organization, we don't take away their super admin status. So if the org is private and the user is a super admin, when they auth back in, we add them back to the default organization.

Additionally, if we create a user through the user API, and that user had previously existed and had super admin status, when they are added, they retain their super admin status.

The motivation for this behavior is to prevent super admins from being removed from every organization, which is possible since admins can remove super admins from any organization they are a part of.

Was either of these the behavior you were seeing, or was it something different?
