### ISSUE TITLE
As a user I can see a global users page

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2613]
This should be

-  [x]  a tab in the chronograf admin page
- [x] only visible to superadmins
- [x] global config toggle for "super admin for new users" should be moved here
- [x] list all users and their orgs
- [x] allow super admins to assign a user to an org
- [x] allow super admins to assign super admin status to other users

-  [x]  allow super admins to remove a user from all orgs (delete user, but not blacklist)
- [x] Set default state of "All new users are super admin" to false

**Comment by alexpaxton** [comment]
![chronograf-admin--all-users-v2](https://user-images.githubusercontent.com/2433762/34233486-8ec37560-e59a-11e7-9fea-e26f8034d591.png)

Here's my second pass at a mockup

- Moved `All new users are SuperAdmins` toggle to be in line with the `+ Add User` button
- In the right-most column there is a `Delete` button and a `Add to Organization` dropdown which only appear on hover
  - The `Add to Organization` dropdown should only list organizations the user is not already a part of (to prevent duplicate adds)
- When a user is added to an organization via the dropdown, a deletable "pill" appears in their respective `Organizations` column
  - Clicking the `X` on each pill removes that user from that organization
  - If a user is only part of one organization, the pill features no `X`, directing the SuperAdmin to remove the user via the `Delete` button. This way it is more clear what is going to happen should they take that action

UX things to experiment with:

- Clicking on an organization pill sets that organization as the current one, then takes the user to `Current Org Users` (should hypothetically behave and feel like a filter)
  - This way if the SuperAdmin wants to assign/modify roles within an org, this is a single click to get there
- `Add to Organization` could also work as a multiselect, allowing the SuperAdmin to add/remove the user from multiple organizations at once
  - Would it be clear what happens if they remove a user from all organizations?
- Do we need a warning message when a user is deleted?
  - Is it necessary to explain that the user is not blacklisted?

**Comment by jaredscheib** [comment]
@nhaugo You cool with the above designs? If so I can get started on this.

**Comment by nhaugo** [comment]
They look good to me

**Comment by jaredscheib** [comment]
@nhaugo When a user is added to an organization, should they simply receive the default role for that organization? There is not an option for specifying the role in the current design.

**Comment by nhaugo** [comment]
1) yes
2) yes

**Comment by jaredscheib** [comment]
👍

**Comment by jaredscheib** [comment]
- [ ] @desa This will require some refactoring on the backend to determine the current defaultRole to be assigned to that user, rather than using stale information from the last /organizations request when this tab was loaded, to determine the defaultRole.

**Comment by jaredscheib** [comment]
- [ ] we'll also want some sleek styles revisions/work from @alexpaxton to make the new column layouts of the Current Org Users table and All Users table, including moving over the All New Users Are SuperAdmin, look jazzy.

**Comment by jaredscheib** [comment]
and we'll need to:
- [ ] remove Public from the Default org
- [ ] document these changes

**Comment by nhaugo** [comment]
Two issues, adding a user with a org fails
![saduser](https://user-images.githubusercontent.com/1003269/35892589-dccb75de-0b5e-11e8-98b8-d50e97dcf64f.gif)

And adding an org to a newly created user fails
![sadusertwo](https://user-images.githubusercontent.com/1003269/35892600-e8cc338c-0b5e-11e8-8e29-5b49356ce43f.gif)

**Comment by russorat** [comment]
nice! 🥇
