### ISSUE TITLE
Alert Rule test button which triggers all the alert handlers on a rule. 

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/chronograf#2620]
A button on KapacitorRulesPage next to the name of the rule, 
and/or a button on KapacitorRulePage (during editing and creation of a rule)
The button artificially "triggers" the rule, sending the alert message to all of the alert handlers on the rule.

The benefit of this button in addition to button testing Kapacitor Configs is to (1) test alert handlers that are not in the configuration (http/log/tcp/exec) and (2) test the rule-specific configurations for the alert handlers.

**Comment by afausti** [comment]
@russorat Having the possibility to trigger the alerts for testing would be really great.

**Comment by SimonKrughoff** [comment]
I agree that having a way to trigger the rule from the builder page would be very nice.

**Comment by kfindeisen** [comment]
Any chance this could still be added, if only in Influx 2.0?

**Comment by afausti** [comment]
Still relevant.

**Comment by r-owen** [comment]
Still relevant. I just ran into this today. It is very frustrating not to be able to trigger an alert.

**Comment by sranka** [comment]
Testing depends on data that the user must help with and cannot be generally created by the UI itself. Also, the successful verification of functionality might require long delay(s), depending on the rule's query and type. I cannot imagine a test button to do the testing trick in the UI. Kapacitor offers a command-line tool that lets you test a task with the help of [data sampling](https://docs.influxdata.com/kapacitor/v1.5/working/cli_client/#data-sampling).

I manually test the rule by writing test data to trigger it. Such data can be written directly from Chronograf UI (_Write Data_ button is in the top-right corner of Explorer UI). I can imagine a `Test` button that would open a similar dialog to let the user write (pre-filled when possible) test data to trigger the execution of alerts. There could be also an option to send the data directly to kapacitor, so that such test data are not persisted in influxdb. @russorat @timhallinflux, please advise

**Comment by timhallinflux** [comment]
This isn't testing the work that Kapacitor is doing within the TICKscript... it is simply testing the connectivity between Kapacitor and the Event Handler target.

I would propose:

Define a "test alert" message which can be sent to any of the event handlers. 
When defining the connection between Kapacitor via Chronograf, enable the "test connection" button -- and when that button is pressed, send the test alert message to event handler.

I would attempt to define a canonical message which includes some very basic information and as you walk through the various event handlers, enrich the canonical message/information.  For example, the "level" of the message should be INFO, the text of the message should be something like,"Testing Connection from Kapacitor".

**Comment by sranka** [comment]
Since not all alert handlers support testing, we agreed to add `Send Test Event` to every alert handler section that supports it:

![image](https://user-images.githubusercontent.com/16321466/121378405-75b94500-c943-11eb-81de-2b2377554455.png)

It will do the same job as the kapacitor configuration's `Send Test Event` handler, but the visible additional UI options are also used in the notification.

**Comment by afausti** [comment]
Thanks @sranka this looks like a good option. It will help us to preview the messages.
