### ISSUE TITLE
Change :interval: to not be time wrapped

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#2650]

**Comment by desa** [comment]
Spent some time looking through things. I think that it shouldn't be too hard.

**Migration**
1. Find queries that have `GroupBy.Time == "auto"`
2. Replace `:interval:` with `time(:interval:)`

**Modify `AutoGroupBy`**
1. Just insert the duration value instead of `time(<duration>)`

Will make a first pass at this on Monday

**Comment by desa** [comment]
The one issue that I see, is what should we do about things like `derivative` and `non_negative_derivative`. e.g.

Should we migrate

```
SELECT
derivative(..., 60s)
FROM ...
GROUP BY :interval:
```
to
```
SELECT
derivative(..., :interval:)
FROM ...
GROUP BY time(:interval:)
```

**Comment by nhaugo** [comment]
https://3putt.files.wordpress.com/2010/03/art_bailing_water_from_boat_hg_clr.gif?w=350&zoom=2

**Comment by russorat** [comment]
i haven't seen this causing any issues. will reopen if i find any.
