### ISSUE TITLE
Editing the menu

### ISSUE THREAD

**Issue by leomag** [influxdata/chronograf#2657]
Editing menu items.

**Comment by jaredscheib** [comment]
Hi @leomag, could you describe in more detail what it is you'd like to edit about the menu?

**Comment by leomag** [comment]
Hi @jaredscheib!
I would like to remove some menu items (for example, host list, data explorer) or customize individual menu items for different users.
Still follows the question, how on the main page of the chronograf to remove the news and place the dashboard itself.

**Comment by jaredscheib** [comment]
Thanks @leomag! Great ideas.

Currently users cannot edit the menu or the status page, but thank you for the suggestions. We will discuss and see if/when this would be on our roadmap.

In the meantime, you are always welcome to submit a PR for the changes you'd like to see :)

**Comment by leomag** [comment]
Gut :)
@jaredscheib and where to apply, you can link?

**Comment by jaredscheib** [comment]
If you mean, where to apply the changes... it's a lot of work, so we should solicit a recommendation for @nhaugo on if or how to proceed, first. I wouldn't want you to do a bunch of work and then it turns out that it's not be in line with the product vision.

One suggestion of how to approach this is to start by looking at `ui/src/containers/StatusPage.js` for the Status Page, and `ui/src/side_nav/containers/SideNav.js` for the menu. Both of these modifications that you're requesting, would require user settings to be persisted. These should probably be added to Redux via a new action creator, and then persisted to local storage via `localStorage.js`.

For the Status Page, there could be a toggle to choose what Status Page displays, or alternately you could persist the Status Page's layout to user settings and add the ability to add a cell, which would contain a Dashboard. I'm not sure if we are willing to remove some of the Status Page's contents.

Again, I would wait for @nhaugo before proceeding with any of this, as it may be that we would have specific requirements for work in this area. Thanks again!
