### ISSUE TITLE
allow for a GENERIC_CUSTOM_HEADERS env var generic OAuth

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#2964]

**Comment by jaredscheib** [comment]
The title of this issue prescribes a specific implementation idea, but now that I'm seeing it here, it's not clear _where_ those custom headers would be applied. This issue was suggested in the context of Heroku, which is the only one that seems to need it, so I think the name of this env var should be more specific so the user can know where it's being applied. In this case, it's a custom header for the request to the `/user` endpoint, which is their endpoint for retrieving UserInfo information. So, it seems like a more specific env var like `GENERIC_CUSTOM_HEADER_USERINFO_REQUEST`, or something to that effect, would be clearer and more precise, since there are multiple requests that Chronograf makes to various endpoints: auth, token, and userinfo.
