### ISSUE TITLE
Data Explorer changing the query entered

### ISSUE THREAD

**Issue by joeomc** [influxdata/chronograf#2994]
Using the influx cli client, this query works:
`select sum(offset_ns) as "system_gm_offset_ns" from telegraf.autogen.sfptp_clock where time > now() - 1h AND (clock = 'system' OR source = 'ptp-gm') group by time(1s)`

When I paste that in to Data Explorer it changes it to:
`SELECT sum("offset_ns") AS "system_gm_offset_ns" FROM "telegraf"."autogen"."sfptp_clock" WHERE time > now() - 1h AND "clock"='system' AND "source"='ptp-gm' GROUP BY time(1s) FILL(null)`

How can I get it to execute my query and stop changing it?

I'm using 
chronograf-1.4.2.3
influxdb-1.5.0

**Comment by russorat** [comment]
@joeomc thanks for the issue. i am able to reproduce on my side. we will look into this. The way to get around this now would be to create a Dashboard with a single graph and cell, and use the graph editor instead of the data explorer. Let me know if that works for you.

**Comment by bthesorceror** [comment]
We currently are not getting enough information back in our queryConfig to build this or similar queries. In order to add support then we need to refactor queryConfig to return more information in regards to the where cause (i.e. a tree of operations) that can properly support clauses in parentheses.
