### ISSUE TITLE
Graph has fill when on CEO, but not on dashboard

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3026]
reported by @bunnyevans in https://github.com/influxdata/docs.influxdata.com/issues/1448

- [ ] ensure the fill on graph lines is consistent when switching between the ceo and the dashboard, and when switching between single stat and other graph types.

![kapture 2018-03-21 at 15 17 59](https://user-images.githubusercontent.com/4805997/37740472-1cc9aca4-2d1b-11e8-837b-2d9ce2235ec5.gif)

**Comment by russorat** [comment]
Seems to be an issue switching between single stat and other graph types. I'm refreshing my browser in between.

![kapture 2018-03-21 at 15 38 23](https://user-images.githubusercontent.com/4805997/37741285-02eec190-2d1e-11e8-897f-22191f3d9e86.gif)

**Comment by alexpaxton** [comment]
Switching to `single-stat` and then back to a different graph type will set the fill to none. I think this is because the single stat graph type has more explicit options passed into the dygraphs component.

I think this could be tackled alongside https://github.com/influxdata/chronograf/issues/3027

**Comment by nhaugo** [comment]
![dumpster-fire](https://user-images.githubusercontent.com/1003269/37931965-148fc03e-30fc-11e8-8c42-eee7840d4358.gif)

**Comment by alexpaxton** [comment]
I believe this was completed by #3068

**Comment by russorat** [comment]
looks good to me. @bunnyevans FYI
