### ISSUE TITLE
Create integration tests for ensuring that client navigates as expected when using basepath

### ISSUE THREAD

**Issue by jaredscheib** [influxdata/chronograf#3254]
An integration test is needed to protect against regression on https://github.com/influxdata/chronograf/issues/3141.

When basepath is set and in use, the Chronograf client should be able to navigate around the app and interact with all pages in the app as usual.

A specific test would:
1. start a server with the options `-p=/pineapple --prefix-routes`
1. client visits `{root}/pineapple`
1. assert that the Status Page loads successfully
1. client clicks to navigate to Data Explorer
1. assert that the Data Explorer loads successfully
1. client clicks to create a fully qualified query
1. client navigates somewhere else, and then back to the Data Explorer
1. assert that the Data Explorer loads successfully and the query remains intact.

**Comment by karel-rehor** [comment]
I've added a new story to cover the specific use case described for Data Explorer.  i.e. Create simple query, click to home page, return to Data Explorer, and query and graph should be the same. 

https://github.com/influxdata/bonitoo-selenium/blob/master/src/test/resources/stories/data_explorer/show_explorer/simple_query.story

**Comment by karel-rehor** [comment]
The problem is that selenium/serenity is configured to run against a single fully prepared and running web-service/web-app.  It initializes a webdriver robot that is then directed to a specific base endpoint.  So, it is impractical/complicated to reconfigure and restart the app under test and then to redirect the running webdriver to it.  

So, the cleanest solution is to create a second test suite, with a more complex configuration.  This is the job [chronograf-serenity-eprise](http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/view/Chron-Sel/job/chronograf-serenity-eprise/). The test suite or Jenkins Pipeline requires four basic steps:

1. Configure selenium grid
1. Install and configure the TICK stack (this is where the basepath gets changed)
1. Run the Selenium/Serenity/JBehave test suite
1. Tear down the test environment to save resources and make sure everything is reset for the next test run. 

This means changing the basepath before the Selenium/Serenity/JBehave test suite is run.  
This is done in the second step (http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/job/deploy-tickstack-chron-eprise/), which requires the argument `CHRONO_BASE_PREFIX`.   This means that all of the JBehave stories (JBehave is used to organize the tests using Behaviour Driven Development idioms) that are run in the basic installation, are also run on the installation with a custom basepath (pineapple), this includes the use case presented in the original description (simple_query.story).  

The value for CHRONO_BASE_PREFIX can be found in the log of the setup job (http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/job/deploy-tickstack-chron-eprise/54/console). It is also reported in a DEBUG message in the TestRun job (http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/view/Chron-Sel/job/chrono-selenium-eprise/54/consoleFull). 

I can also provide a log message at the start of the test indicating the full base URL against which the test suite will be run.  Unfortunately the screenshots currently being taken do not include the address bar.  I'll see if there isn't a way to add it next week. 

The latest run is here (N.B. the random base64 strings in these URLs will likely change when the test is next run scheduled for Monday morning 23-7.): 
  * [Create Simple Query](http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/view/Chron-Sel/job/chrono-selenium-eprise/Chronograf_20Automated_20Test_20Report/181348b500ee7105c80e4844db22df287c5ae1b84fabbbfeecaa46f76912e4e2.html)
  * [Leave Data Explorer and Return ](http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/view/Chron-Sel/job/chrono-selenium-eprise/Chronograf_20Automated_20Test_20Report/ba37227f55e55ce5a00d33be0312f011e83860294871acaa90a6111cedc88c32.html)

**Comment by jaredscheib** [comment]
@karel-rehor Thanks so much for the detailed response. Super helpful to get insight into how our integration testing works, and why we have the Enterprise version. I understand from what you're saying that we apply the `CHRONO_BASE_PREFIX` there, and I see it in the links you sent.

As you mentioned, I agree that two things that would be helpful for confirmation are:
1. log message that shows the command run when starting the Chronograf server, so that it's clear that `--basepath`/`-p` is being set to the value of `CHRONO_BASE_PREFIX`;
1. a URL bar in the screenshot output, ideally both in the non-enterprise and the enterprise versions of the tests

Could you let me know if you've been able to capture (1) and if (2) will be possible going forward?

Seeing the URL bar will also be helpful for confirming things like template variables being synced with the URL query params.

Thank you again.

**Comment by karel-rehor** [comment]
@Jared - unfortunately the selenium driver only permits screenshots within the browser window without the frame or controls.  So currently the URL address bar cannot be included.  I have, however done 2 things. 

1. I've added an environment variable dump into the test log,
1. I've added a test step to write the current URL into the test report.  This step can be used in scenarios, where knowing the full URL is important, e.g. dashboard_urls. 

The log dump can be seen, for example, [here](http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/view/Chron-Sel/job/chrono-selenium-eprise/63/consoleFull) (N.B. the full log is long and can take a few seconds to load).  Scroll down a few lines to this section: 

```
...
(BeforeStories)
INFO  c.b.i.c.a.jbehave.RunTestSuite - SERENITY CONFIG
INFO  c.b.i.c.a.jbehave.RunTestSuite -    BASE URL:   http://172.31.25.203:8888/pineapple
INFO  c.b.i.c.a.jbehave.RunTestSuite -    TEST COUNT: 0
INFO  c.b.i.c.a.jbehave.RunTestSuite -    ENVARS:     
INFO  c.b.i.c.a.jbehave.RunTestSuite -       awt.toolkit:   sun.awt.X11.XToolkit
INFO  c.b.i.c.a.jbehave.RunTestSuite -       testdata.noaa.waterbase:   testdata/NOAA_data.txt
INFO  c.b.i.c.a.jbehave.RunTestSuite -       serenity.restart.browser.for.each:   never
...
```
The write of the URL in the test report can be seen, for example, [here](http://ec2-13-56-214-192.us-west-1.compute.amazonaws.com:8080/view/Chron-Sel/job/chrono-selenium-eprise/63/Chronograf_20Automated_20Test_20Report/0bc9f2fe3ec12d78d92e86b9ebea2647adf4a81b1a1ca552981ab4537fb0d6f6.html).  Expand the line 'When capture current url to the report'.  

e.g.
```
http://172.31.25.203:8888/pineapple/sources/1/dashboards/32?tempVars%5Bhost%5D=%27cluster_node_1%27&lower=now%28%29%20-%205m
```

I hope this will help in understanding the results.

**Comment by jaredscheib** [comment]
@karel-rehor Thank you again for this comprehensive response and diligence. These reports do appear to substantiate that basepath is indeed being used successfully – thank you for providing these, for adding the log output and the URL test report step, and for confirming all of this. Much appreciated!
