### ISSUE TITLE
add the ability to enable/disable an alert node config

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3292]
Right now, there is no way to "unset" an alert node config in the Kapacitor UI. We should add that ability.

- [ ] determine if we can toggle enable/disable for kapa configs
- [ ] add the option to enable / disable to the ui.
- [ ] ensure we can use this to remove the deprecated notice in the UI

**Comment by russorat** [comment]
required for #2786 and #2904

**Comment by alexpaxton** [comment]
![screen shot 2018-05-03 at 9 32 01 am](https://user-images.githubusercontent.com/2433762/39590204-134c45ea-4eb5-11e8-98f5-ea76238c2268.png)

Use a `ConfirmButton` here to prevent accidental resets. Using the language "Reset" because all this should do is set all the values back to an unconfigured state, rather than deleting anything. This action should remove the green checkmark in the alert tab as well, which will indicate to the user that the action was effective

**Comment by alexpaxton** [comment]
Also, the use case of disabling doesn't make a ton of sense to me. Not sure why someone would want to turn off a config but preserve the values (which is what "disable" means to me) and then re-enable later
