### ISSUE TITLE
Show nanosecond timestamps in Log Viewer

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#3839]
The chronograf backend has this, and it would be nice for the frontend to support this:

```json
{
   "query:" "select * from cpu",
   "epoch": "ns"
}

```

My specific need is for logs; I need the full precision nanoseconds so I can get the logs to render in the right order.

**Comment by russorat** [comment]
@goller where would this be surfaced in the UI? logviewer? data explorer? dashboards? all?

**Comment by goller** [comment]
@russorat 
1. for logviewer I think the query needs to be epoch nanos and could just format to milliseconds; no need to expose the option here because logviewer is trying to simplify the log viewing experience.

2. for dashboards it feels like a format option ... maybe here?
<img width="440" alt="image" src="https://user-images.githubusercontent.com/1922921/42704689-7441c046-8696-11e8-8026-35c25efe8fbe.png">

or perhaps here for both dashboard and data explorer:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/1922921/42704716-8ca86c2a-8696-11e8-933e-eab4a549d39d.png">

**Comment by scipetr** [comment]
This is still a problem.

**Comment by dangoodman** [comment]
Table visualization just misses log messages appeared in the same millisecond. It's misleading at least. Nanosecond precision support is a must I think.

**Comment by russorat** [comment]
@dangoodman thanks for bumping this. Looks like a small change with a big impact so I've added it to the next maintenance release of chronograf.

**Comment by dangoodman** [comment]
@russorat thank you. Looking forward.

**Comment by sranka** [comment]
Milliseconds are used under the hood in the UI to fit into javascript number type, such numbers are then used in various transformations. A nanosecond time cannot be stored into a javascript number without losing precision. A JS bigint type might be `candidate` for the future representation of time, but it cannot be simply used for what was done in the past. Nanosecond precision computations and transformations in the UI would require a new major version of Chronograf. The goal herein is to find a way for Log viewer table visualization to show and sort with full nanosecond timestamp. If feasible, a secondary target is a solution for a table visualization component that is used dashboard and explorer UI.

**Comment by sranka** [comment]
Numbers greater than 9007199254740991 lose precision during JSON parsing of query results in the browser transport layer. Today's nanosecond timestamps are always bigger to fit into javascript number.

Solution for a log viewer table is to query also a `timestamp % 1000000`, which gets nanoseconds  in a particular millisecond. A precise timestamp (nanos) can be then computed as `String(Math.floor(timestamp/1000000)) + String(timestamp % 1000000).padStart(6,0)` .

**Comment by dangoodman** [comment]
Just want to emphasize the importance of the issue. 

One might think it's not a problem for regular apps generating small amounts of events. That's not true since often an app generates a **bunch of related events** almost instantly even if this app is a script you run once a month. For example, if an app loads a configuration file it might log something like:
[000ns] Couldn't open file /tmp/config.yml. Not enough permissions.
[500ns] Couldn't load config: file read error.
[700ns] Failed to start service: config loading failed.

Now guess which of those entries you would see in your dashboard? However, it doesn't matter since seeing just one of those entries would be misleading anyway.

**Comment by sranka** [comment]
@dangoodman you will see all the results in dashboards since Chronograf 1.8.6 (see https://github.com/influxdata/chronograf/pull/5553). The results will be sorted properly with `ORDER by time DESC`.

**Comment by sranka** [comment]
To recapitulate the state of Chronograf 1.8.9:
1. UI table visualization shows all query results (even in the same millisecond) in the right order when `ORDER by time DESC` is used. It is however not possible to visualize the exact nanoseconds time, the precision is lost because it cannot fit into browser (javascript) number. Additionally, InfluxQL does not allow to cast `time` to string or manipulate the `time` as a new query field, there is no workaround in InfluxQL to use. Users can however switch to flux queries to cast time to string or return nanosecond fractions that can be then visualized to know exact nanoseconds, it is the only solution to go with. A flux part that will add UTC nanosecond time would be : ` |> map(fn: (r) => ({r with nsTime:string(v: r._time)}))` or `|> map(fn: (r) => ({r with nsInMs:int(v:r._time) % 1000000}))`
2. Log Viewer shows all items in the order they arrived to telegraf, the timestamp column however does not contain a precise nanosecond time of a syslog message, the precision was lost during conversion to javascript number. A solution for this is in progress, a query will return nanosecond fractions so that a full precision timestamp can be recomputed in the LogViewer UI.
