### ISSUE TITLE
template variables overridden when I paste a URL into browser with template variables

### ISSUE THREAD

**Issue by goller** [influxdata/chronograf#3909]
(master from today):

I pasted this:

http://chronograf.internal/sources/5000/dashboards/44?tempVars%5Bapp%5D=queryd&tempVars%5Bcondition%5D=&lower=now%28%29%20-%205m#

but,
when the page renders it changes the dashboard to:
http://chronograf.internal/sources/5000/dashboards/44?tempVars%5Bapp%5D=storage-6&tempVars%5Bcondition%5D=&lower=now%28%29%20-%205m

The difference is the app parameter;  storage-6 was my parameter before I clicked on the link.

**Comment by russorat** [comment]
the values in the url are supposed to take precedence over any values stored in local storage as long as the values are valid. cc @jaredscheib

**Comment by chnn** [comment]
I'm having trouble reproducing. When the dashboard loaded, was `queryd` still a valid value for the `:app:` template variable?

I believe the expected behavior is:

- If `queryd` is a valid value for the template `:app:`, then the dashboard should render with `queryd` selected (and still reflect that in the URL)
  - If `queryd` is not a valid value for the template `:app:`, then the default value for `:app:` should be selected (i.e. the value that is marked as `selected` in the DB server-side).
    - If the default value for a query param is not valid, then the first value for `:app:` is selected

@goller Any easy way I could take a look at that dashboard? I haven't set up the VPN yet.

**Comment by chnn** [comment]
@goller It looks like `queryd` is not a value for the `:app:` template variable, but `query` is. Not sure how `queryd` got in the URL, did the name change recently? 

The following link is working for me (replaced `queryd` with `query`):

http://chronograf.internal/sources/5000/dashboards/44?tempVars%5Bapp%5D=query&tempVars%5Bcondition%5D=&lower=now%28%29%20-%205m

**Comment by goller** [comment]
@chnn the template variable wasn't queryd but query.  It was automated links from kapacitor.
