### ISSUE TITLE
Bug fixes for Text template variables

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#3967]
- [x] creating a text template variable and then using it in a query fails because the blank value is not substituted in until you focus on the text box and hit enter
- [x] refreshing the dashboard doesn't respect the text input template variable
- [x] adding a garbage value into the text template variable type should break the graph

**Comment by chnn** [comment]
My guess is that a some or all of these bugs are due to not correctly tracking template variable value `selected` / `localSelected` during hydration.

25b3a3d89 and 9eb897cce attempted to address similar issues. We should extract the following utilities to a separate module and rewrite them as a `switch` statement that handles each and every `TemplateType` explicitly: https://github.com/influxdata/chronograf/blob/25b3a3d89ce3ab5ee0423603d6b45b56caa734a4/ui/src/tempVars/utils/graph.ts#L243-L315

**Comment by russorat** [comment]
@chnn verifying that these updates have been cherry picked into 1.6.x branch?
