### ISSUE TITLE
Chonograf on windows show up as red down(status) when not using the "default" database.

### ISSUE THREAD

**Issue by cjpit** [influxdata/chronograf#4411]
I have my windows data going to a non default database as per something like this:
`[[outputs.influxdb]]
  urls = ["https://xxxxxx"] 
  database = "windows" `

I note in the fix https://github.com/influxdata/chronograf/issues/1794 that the uptime is hardcoded to a specific db which, in my case is not correct.

I would expect it to use similar query as the other items above it, eg in line 13 of ui/src/hosts/apis/index.js
`SELECT non_negative_derivative(mean("System_Up_Time")) AS winDeltaUptime FROM win_system WHERE time > now() - 10m GROUP BY host, time(1m) fill(0);
      SHOW TAG VALUES FROM /win_system|system/ WITH KEY = "host"`

**Comment by russorat** [comment]
@cjpit thanks! when you configure a source in chronograf, you have the option of setting the "Telegraf Database Name" for that source. By default, we use `telegraf` but in your case, you want to change it to `windows`. You can also change the retention policy so that it doesn't use the default `autogen` but whatever you set in your telegraf config. From there, the query will look for the `win_system` measurement using the database `windows`.

![image](https://user-images.githubusercontent.com/4805997/45374322-955e8b80-b5a6-11e8-87fe-fb9a9ad21cc1.png)

Please reopen if that doesn't work for you.

**Comment by cjpit** [comment]
Thanks russorat, yeah I had those settings in place.  I was looking at old code by the looks. I just took a snap of the data coming back from the json query on the client, and it seems the last datapoint is always returning zero.  ![image](https://user-images.githubusercontent.com/3469512/45398606-7b40ae00-b677-11e8-8031-98280e1bfe74.png)

Could this be a timing issue eg I have datapoints sent every 20s?

Thank you

**Comment by cjpit** [comment]
Resolved, my bad - time sync was out.
