### ISSUE TITLE
logviewer should display line protocol timestamp

### ISSUE THREAD

**Issue by dgalichet** [influxdata/chronograf#4573]
Hi,

on actual logviewer, there is a column 'timestamp' that is based on field 'timestamp' from data input.

Fields timestamp are sometimes in other format (ISO8601 for example), but we convert this timestamp to an epoch in ns as required by influxdb line protocol.

Why not simply use timestamp from line protocol (so we would also be coherent with data explorer table views in chronograf) ?

Regards

**Comment by russorat** [comment]
@dgalichet it sounds like you would like a way to configure the formatting of the syslog timestamp column as well as the ability to display the line protocol timestamp. Is that correct?

We show the timestamp column because the time the log line is inserted into influx isn't always the same time as the log line due to batching or a delay in sending the log line. We assume that the timestamp for the log line is the most accurate one.

**Comment by dgalichet** [comment]
@russorat yes exact. Having flexibility on the displayed columns should be an heavy progress in our sense on LogViewer. In a more general way, not being locked on syslog protocol would be a great improvement.
