### ISSUE TITLE
The date format selected in the table view should propagate to the CSV download

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#4858]
as a chronograf user
with editor permissions or higher
when i export the data in my table as a CSV
then i would like the date format to be what i have selected for the visualization

right now it is sent in a fixed format: https://github.com/influxdata/chronograf/blob/master/ui/src/shared/parsing/dataToCSV.js#L6

once we have this, we should also make the change in the `fix/add-nanoseconds` branch

**Comment by geniusled** [comment]
bringing up this issue, currently for some simple task we are exporting CSV in order to import into a excel/google sheet doc for tracking purpose. AM/PM with 12h format is very inconvenient for excel formulas (to calculate durations)
its quite annoying that the datetime format used in the CSV export does not match any other time format used in chronograf.
exporting in UTC would be good, but as russorat highlighted, matching the date format used in visualization would be most modular and long term approach
