### ISSUE TITLE
Chronograf display Kapacitor tickscript status

### ISSUE THREAD

**Issue by Pwalne** [influxdata/chronograf#4911]
Chronograf is advertised as "the UI for kapacitor" but there is no way to view the currently 'active' alerts that have been triggered by defined tickscripts in kapacitor. There is no reason an alert rule should have to be created for an already defined tickscript just to see what it's state is.

Example:
If i defined a tickscript in kapacitor (or even create a new one in chronograf) and set it's parameters to fire off in a state I cannot view that alert state in any way in chronograf. This seems to be overlooked and the only kind of alert that can be viewed is a alert rule.

**Comment by russorat** [comment]
@Pwalne the alert list in Chronograf will only show alerts that were created using the Alert Rule Builder in the UI. This is because those alerts have a special `InfluxDBOut` node in them to store the data in the `chronograf` database in a specific format.

What is the equivalent kapacitor CLI command that gives you the information you are looking for?

**Comment by Pwalne** [comment]
A equivalent kapacitor CLI command would be 
```
kapacitor show-topic <topic> 
```
Where <topic> could be obtained by executing 
```
kapacitor list topics
```
