### ISSUE TITLE
TICKscript editor scroll issues in Firefox

### ISSUE THREAD

**Issue by dataviruset** [influxdata/chronograf#5037]
Similar to this issue, but in the TICKscript editor.
https://github.com/influxdata/chronograf/issues/4822

Firefox 64.0 on Ubuntu x64

No scrollbar, can't scroll down, and if I go down using my keyboard, it seems impossible to go up.
The screenshot is of my entire browser window, so the problem is that the height of the edit box isn't limited, I guess.
Didn't have problems with Chronograf 1.6.2.

![screenshot from 2019-01-13 14-33-53 2](https://user-images.githubusercontent.com/1078018/51082488-b4cb1800-1742-11e9-8a13-6953b3bb888b.png)

**Comment by OlegKorchagin** [comment]
confirm the bug. 
TICKscript Editor, scrolling in the editor field does not work in firefox, but works in chrome and chromium

environment:
* chronograf 1.7.9-1, x86_64, debian 9
* chronograf 1.7.3-1, x86_64, rhel 7

Steps to reproduce:
open TICKscript Editor ( chronograf web page -> Alerting -> Manage Tasks -> TICKscript ( bottom list ), select any script
* firefox ( last version ) : scrolling in the editor field does not work, so editing the script is almost impossible. Looks like editor vertical size is much more than actual browser windows height
* chrome and chromium ( last version ) : works fine
https://imgur.com/a/5udW9Pk

expected behavior:
scroll in TICKscript Editor works in firefox

**Comment by OlegKorchagin** [comment]
![Снимок экрана от 2019-05-11 12-07-39](https://user-images.githubusercontent.com/8507635/57567728-50655000-73e6-11e9-9baa-03b4b0fe1521.png)

**Comment by sdicataldo** [comment]
we have the same issue, making the chornograf binary from the source code.
Any idea how to fix this issue?

**Comment by sdicataldo** [comment]
Hi found a very raw solution, from the source code Page.scss

I added overflow-y to the class css .page

.page {
  display: flex;
  flex-direction: column;
  align-items: stretch;
  flex-wrap: nowrap;
  flex: 1 0 0;
  width: calc(100% - 60px);
  overflow-y: scroll;
}

With this update the tickscript-editor div never go down a lot to hide the top button area.

**Comment by brice86** [comment]
Same problem with Firefox 67.04 64-bit, Windows 10

**Comment by joriws** [comment]
1.7.12 tick editor and latest firefox.

If I edit long script file like so many rows that your UI scrolls, my Chronograf top row scrolls away and I can no longer save the tickscript because I cannot get back to top chronograf row where green save button is..

I can circumvent this with Firefox take screenshot function which scrolls and reveals to top row. But before learning this trick there was no way to save.

**Comment by gtjamesa** [comment]
I'm having the same issue with Firefox 70 on Windows 10 Pro, running Chronograf 1.7.14

**Comment by camccar** [comment]
Also having this issue in Windows 10, latest chronograf and firefox

**Comment by Marbaf** [comment]
Same issue with Chronograf 1.7.17 and Firefox 74.
How come you don't use Firefox? Come on you just hired a guy from Mozilla according to your blog.

**Comment by dp1140a** [comment]
This issue is over a year old.  Is there any movement on it?
