### ISSUE TITLE
Add support for InfluxDB behind reverse proxy under subpath (https://example.com/influxdb/)

### ISSUE THREAD

**Issue by oddstr13** [influxdata/chronograf#5096]
Currently (Chronograf 1.7.8), attempting to add a InfluxDB connection with Connection URL of `https://example.com/influxdb/` results in a ping request to `https://example.com/ping` (path part of url is replaced, not appended to).

Desired behavior would be a request to `https://example.com/influxdb/ping` (path relative to supplied URL).

**Comment by russorat** [comment]
@oddstr13 We are having trouble reproducing this issue. Can you provide some additional details about your setup? When we check the code, it should be using the full url you enter in the source connection before adding the `/ping`. Are you still seeing this issue?

**Comment by oddstr13** [comment]
This is the relevant part of my nginx server block;
```nginx
    location /influxdb/ {
        proxy_pass http://localhost:8086/;
    }
```
Seeing as the application didn't even connect, I ended up digging into the influxdb command-line interface and syntax to do what I needed.
I have not used this application since my initial failed attempt, and as such cannot tell if the issue is still present or not.

**Comment by dontsovcmc** [comment]
influx cli also unsupported path in url: https://github.com/influxdata/influxdb/issues/10294
=(((

**Comment by camimartinez** [comment]
The issue is still happening at **chronograf 1.8.8**, i need to configure the influxdb behind a proxy reverse with a sub path like this: "https://myhost/influxdb" and it seems that chronograf is changing the url when is querying the influxdb "ping" endpoint (with a sub path), the logs show the following:

`Failed to retrieve database version" error="<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /ping was not found on this server.</p>\n<hr>\n<address>Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips Server at myhost Port 443</address>\n</body></html>\n`

And after that the following error appears:
`level=error msg="Error message Error contacting source" component=server http_status =400`

Can you support the sub path? or any work around to this? Thank you.

**Comment by Forbzy** [comment]
Hi All
What are the subpath configuration need in chronograf? When I load influxdb via browser I just see a white blank screen.

**Comment by DrPinguin98** [comment]
> 
> 
> Hi All
> What are the subpath configuration need in chronograf? When I load influxdb via browser I just see a white blank screen.

Yep, same with InfluxDB

**Comment by Forbzy** [comment]
I think I read somewhere that influxdb used to come with a frontend UI. But that got removed in a previous version. You can use Chronograf or Grafana instead and hook them up to Influxdb.

Kind Regards

James

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by oddstr13** [comment]
@russorat I can confirm that this is still an issue in Chronograf v1.9.0

**Comment by sranka** [comment]
Yes, the custom InfluxDB path is still not supported in 1.9.0

**Comment by tlifschitz** [comment]
Please can someone make an effort to move forward with this feature? Im afraid i have no knowledge of Go. It a pitty not being able to access such a useful UI when running influx behind nginx and in a subpath.

**Comment by oddstr13** [comment]
@sranka Thanks for looking into this!
I'm looking forward to testing out the next release :slightly_smiling_face:

**Comment by sranka** [comment]
@oddstr13 you can already give it a try with a chronograf nightly build, that can be downloaded from https://portal.influxdata.com/downloads/

**Comment by oddstr13** [comment]
Tested the docker image, seems to be working fine.
Thanks for fixing the issue! :smiley:
