### ISSUE TITLE
Why is this licensed as AGPL

### ISSUE THREAD

**Issue by ericallenhoffman** [influxdata/chronograf#5173]
Why does this component not use the same license as influxdb (MIT)?

**Comment by timhallinflux** [comment]
See: http://docs.influxdata.com/chronograf/v1.7/about_the_project/

Chronograf is released under the GNU Affero General Public License. This Free Software Foundation license is fairly new, and differs from the more widely known and understood GPL.

Our goal with using AGPL is to preserve the concept of copyleft with Chronograf. With traditional GPL, copyleft was associated with the concept of distribution of software. The problem is that nowadays, distribution of software is rare: things tend to run in the cloud. AGPL fixes this “loophole” in GPL by saying that if you use the software over a network, you are bound by the copyleft. Other than that, the license is virtually the same as GPL v3.

To say this another way: if you modify the core source code of Chronograf, the goal is that you have to contribute those modifications back to the community.

Note however that it is NOT required that your dashboards and alerts created by using Chronograf be published. The copyleft applies only to the source code of Chronograf itself.

If this explanation isn’t good enough for you and your use case, we dual license Chronograf under our standard commercial license.
