### ISSUE TITLE
Using chronograf api to create dashboards doesn't respect id field

### ISSUE THREAD

**Issue by perzizzle** [influxdata/chronograf#5291]
We store our dashboards in source control so that we can migrate them through our environments. If we do an http post to http://$chronograf/chronograf/v1/dashboards/ a dashboard is created but it doesn't create it with the same id as in the http post body. My reading of the api docs says the v1/dashboards endpoint accepts an id field. 

I would expect if we post with id 1, a dashboard with id 1 will be created. If a dashboard with id 1 already exists, I would expect the request to return a non-200 response code.

**Comment by glinton** [comment]
I believe this was a documentation error, which if I understand correctly, was effectively closed by #5295.

You can store the dashboard json (that you post to the API) in files ending with `.dashboard` and place those files in the directory referenced by the flag `--resources-path` used on chronograf start and those ID's will be respected.

I may have misunderstood something, so if this issue is in fact an open feature request, comment and we'll re-open it. Cheers
