### ISSUE TITLE
Chronograf UI tickscript Alert name does not change when using template names

### ISSUE THREAD

**Issue by tnedev** [influxdata/chronograf#5403]
I'm using Chronograf 1.7.16 in a Docker container. 

I've made a tickscript template to use for a few alarms. 
When I make those alarms by providing variables from json, the alarm works just fine and it uses the variables correctly, but the Chronogaf's UI uses the old variable name, instead the one provided in the json.
This makes all alarms from the template use the same name in the UI and it gets confusing.

**Comment by russorat** [comment]
@tnedev thanks for opening this. I'm not saying this is the desired behavior, but I believe the UI pulls the name of the TICKscript from a `var name = 'Custom Rule Name'` in the script. Otherwise, it uses the `id`. If you want a nice name in the UI, can you try adding a `var name =` line to your template and seeing if the UI picks that up?

**Comment by tnedev** [comment]
@russorat thanks for replying. 
If I understood you correctly, I already have **var name** in my template and the UI is picking it up. However, the UI is not picking the updated name after the json with the vars is passed. So the actual alarm is using the name from the json, but the UI is using the one from the template.

**Comment by sranka** [comment]
Kapacitor task vars are currently ignored when extracting the task name to render in the UI. It could be however enhanced to use the vars in https://github.com/influxdata/chronograf/blob/master/kapacitor/client.go#L96
