### ISSUE TITLE
Unable to configure idle connection timeout on Influx connections

### ISSUE THREAD

**Issue by pbackx** [influxdata/chronograf#5583]
We are running Chronograf and Influx on AWS. The connection from Chronograf to Influx goes through an AWS load balancer (network ELB).

This ELB has an idle connection timeout of 350s [1] that cannot be changed.

We are experiencing regular "400 connection reset" errors on the Chronograf-Influx connection. I believe this is because Chronograf uses a larger connection timeout.

I've looked around [2] and it does not appear that I can change that idle timeout. 
A quick look through the code [3] seems to confirm my suspicion, but I'm not a Go developer, so I may be mistaken.

Could you guys look into this? It is especially annoying to some of our users on less-frequently used system.

[1] https://docs.aws.amazon.com/elasticloadbalancing/latest/network/network-load-balancers.html#connection-idle-timeout
[2] https://docs.influxdata.com/chronograf/v1.8/administration/creating-connections/#manage-influxdb-connections-using-src-files
[3] https://github.com/influxdata/chronograf/blob/master/influx/influx.go#L26

**Comment by sranka** [comment]
Thank you @pbackx for reporting an issue. There is no idle timeout set now.

A clone of http.DefaultTransport should fix this, as you pointed out in https://github.com/influxdata/chronograf/blob/master/influx/influx.go#L26, the idle connection timeout would be then 90 seconds (as well as other reasonable defaults).

I also verified connections to kapacitors, they are not affected since a default (or a clone of it used) in https://github.com/influxdata/chronograf/blob/5cd8cc7cddbe6e816f6bc479114291543eba1b14/server/proxy.go#L74
