### ISSUE TITLE
Set password for chronograph

### ISSUE THREAD

**Issue by Justarrive** [influxdata/chronograf#5601]
Hello,

is there a possibility to secure chronograph with a password. I know that there exits OAuth2. But I thought, that
if you connect it to Google everyone, who has a Google-Account could connect to chronograf?

Best regards,
Justarrive

**Comment by sranka** [comment]
Chronograf (since 1.8.7) can be configured with basic access authentication (user name + password), see
 https://github.com/influxdata/chronograf/pull/5577 for details. If users authenticate through an OAuth provider, an administrator still controls the that can enter since users without roles are forbidden then (unless [All new Users are Super Admins](https://docs.influxdata.com/chronograf/v1.8/administration/managing-chronograf-users/#all-new-users-are-superadmins-configuration-option)).
