### ISSUE TITLE
Refused to execute script because its MIME type ('text/plain') is not executable

### ISSUE THREAD

**Issue by r3verser** [influxdata/chronograf#5607]
Getting error in browser console when trying  to open http://localhost:8888/
```
Refused to execute script from 'http://localhost:8888/src.b6c09643.js' 
because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```
**chronograf-1.8.7-1**, **Win 7**
:neutral_face:

**Comment by spehj** [comment]
Same error here. Only black screen appears when trying to open http://localhost:8888/

**chronograf-1.8.7-1, Win 10 Home**

**Comment by sranka** [comment]
@r3verser @spehj it was already reported in https://github.com/influxdata/chronograf/issues/5565, but I was not able to reproduce it. So it probably depends on Windows configuration and the newest 1.8.8 version will not make the situation better. A workaround and root cause is likely described in https://github.com/golang/go/issues/32350 , can you please give it a try and let me know?

**Comment by r3verser** [comment]
@sranka thank you, changing registry values helped, now everyhting works fine! :+1: 
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.js]
"Content Type"="text/javascript"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\.js]
"Content Type"="text/javascript"
```

**Comment by sranka** [comment]
No windows workaround is required since 1.8.9, #5622 ensures that '.js' files are always served with `text/javascript` content-type.
