### ISSUE TITLE
News feed -- fails to load

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#5638]
Need to adjust URL from https://influxdata.com/feed/json 
to https://www.influxdata.com/feed/json

Redirect is failing.

**Comment by sranka** [comment]
@timhallinflux the webserver now returns a fresh feed also at https://influxdata.com/feed/json, but the feed data cannot be displayed in chronograf UI because of missing CORS headers. Chronograf home page now shows

![image](https://user-images.githubusercontent.com/16321466/102251036-8e9cec80-3f04-11eb-8039-c3ef0dff3ab6.png)

browser console contains the root cause:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://influxdata.com/feed/json. (Reason: CORS request did not succeed).
```

**Comment by sranka** [comment]
influxdata.com web server has been fixed
