### ISSUE TITLE
Chronograf in chrome browser - request are stalling intermittently

### ISSUE THREAD

**Issue by KannappanSomu** [influxdata/chronograf#5657]
Chronograf in chrome browser - request are stalling intermittently when browsing data in chronograf alerts / explorer tab .
what could be the reason ? I m running version 1.8.0 of chronograf 

![image](https://user-images.githubusercontent.com/55806176/104045614-2083d680-51df-11eb-9615-98d47dc7b31a.png)

![image](https://user-images.githubusercontent.com/55806176/104045717-3f826880-51df-11eb-83dc-e64ce228e6b9.png)

**Comment by kannappan-v** [comment]
Observation is that , kapacitor backend  api **/kapacitor/v1preview/logs** api is taking too long to respond and thats the reason chronograf page goes blank intermittently every time when we open a tick script. 

Why does chronograf posts request to kapacitor at path **/kapacitor/v1preview/logs?=taskname** , when logging is not slected in chronograf UI ?  Is this a bug

**Comment by sranka** [comment]
The current state is that the logs are read asynchronously when opening a task detail, independently on whether `Editor + Logs` is selected or not. It reads a stream of data, so it is kept open and can appear in an infinitelly pending state. The actual defect (that I found during review) is that the stream is not properly closed when you leave the task detail page.

The suspicious point from your descrioption is that `/kapacitors` is also in a pending state. It means that it waits for chronograf backend to serve quite a simple response that uses its internal store. :thinking:  

Finally, I was able to reproduce this. It does not happen right after your open the browser, but after you open details of several tasks. It then keeps several task log stream open (pending state), the Chrome connection limit is reached and all UI communication to the server becomes pending. If I open another browser/session, it works fine.

After I exprimentally comment the `logs retrieval` part https://github.com/influxdata/chronograf/blob/c61e25171bad3321b1679749307a8fe866873142/ui/src/kapacitor/containers/TickscriptPage.tsx#L147

, there are no pending connections and everything seems to work fine. The root cause is for sure the inappropriate destruction of a Tickscript page where the logs stream is not properly closed.

**Comment by kannappan199** [comment]
Thanks for your comments. How Do we resolve this from our side ? 

as of now i m using HTTP redirection  rule to forward request made to 
**logs api --> ping api**

**Comment by sranka** [comment]
There is no better workaround now, the ping response is finite and quickly closes the reader.

**Comment by kannappan199** [comment]
OKay, So this will be opened as a bug ?

**Comment by sranka** [comment]
Yes, it is.
