### ISSUE TITLE
 Chronograf tables

### ISSUE THREAD

**Issue by shaharzeira** [influxdata/chronograf#5659]
This is a feature request

Be able to define a table when rows can be selected as the measurements, tag keys, and field keys (if not all have the data, then it should be empty), in a similar way to define graphs that can be saved as cells. As of now, it is not possible for my knowledge. This will make Chronograf be the best tool for representing data (and not only the best tool for creating graphs).

**Comment by sranka** [comment]
Thank you @shaharzeira for reporting an issue. A table can be configured with time on the horizontal axis so that rows represent fields or tags in time. Feel free to reopen this issue with an example of what it should look like. It is not clear to me what is exactly being requested herein.

```
SELECT "numMeasurements","hostname" FROM "_internal"."monitor"."database" WHERE time > :dashboardTime: AND time < :upperDashboardTime:
```
![image](https://user-images.githubusercontent.com/16321466/131444745-a6b40fe7-969e-4c78-b853-8f0b80017647.png)
