### ISSUE TITLE
Chronograf HA: Roles for InfluxDB enterprise appear to be broken

### ISSUE THREAD

**Issue by russorat** [influxdata/chronograf#5695]
customer has reported the following:

when chronograf is configured to connect and store data in etcd (chronograf HA configuration), and when that chronograf is connected to an InfluxDB enterprise instance, the InfluxDB Admin -> Roles page is not functioning. The user is unable to edit or change roles form chronograf. the user reports that this previously worked when using bolt.

Related https://github.com/influxdata/EAR/issues/2123

**Comment by sranka** [comment]
I tried both bolt and etcd to prove that this issue is reproducible independently on the type of chronograf store. The issue has its roots in the understanding of the communication between meta nodes.

AFAIK any meta node can directrly return the data (roles), but only the leader node (selected automatically to properly manage state replications between meta-nodes) can modify the data (create/update/delete roles). When a non-leader node receives a request to modify the data, it simply redirects the client (chronograf server in our case) to the leader node using standard HTTP redirect to URL with leader [hostname](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-meta-nodes/#global-options). If the network where the chronograf server cannot access the leader hostname, the connection timeouts after 60 seconds and the request fails. 

I can reproduce the same issue with a locally installed chronograf against InfluxDB enterprise in AWS with meta nodes configured without a hostname (detected). Redirects to the leader node then contain an address that is not visible to chronograf. The chronograf log then contains:
```
ERRO[3763] Error message Post "http://10.2.1.50:8091/role": dial tcp 10.2.1.50:8091: connect: connection timed out  component=server http_status =400
```

The solution for HA is
1. Use a load balancer proxy in front of the meta nodes, configure chronograf with the balancer proxy.
2. Ensure that redirects from non-leader to leader nodes contain URLs that are visible to the chronograf server. This can be achieved by configuring each meta node with a hostname [hostname](https://docs.influxdata.com/enterprise_influxdb/v1.8/administration/config-meta-nodes/#global-options) that is visible to other meta nodes and also to the chronograf server.

Code review reveals some things that have to be fixed in chronograf as well:
1. The meta client implementation automatically switches the communication to the [last known leader](https://github.com/influxdata/chronograf/blob/36207fb5fdd22639e611d4f6f31cdd0c27f845ee/enterprise/meta.go#L387). Such approach disrupts failover principles that a load-balancing proxy can provide. The impl always has to use the configured (eventually proxy) Meta URL.
2. The dial timeout of 60 seconds makes this issue quite hard to identify, it would be ok to fail after 10 seconds.

**Comment by timhallinflux** [comment]
thanks @sranka great investigation and write-up
