### ISSUE TITLE
Unable to save multiple queries to dashboard cell

### ISSUE THREAD

**Issue by timhallinflux** [influxdata/chronograf#5703]
Use Data Explorer to create a new query.
Now, create a second query on a separate query tab as shown here:
![Screen Shot 2021-03-14 at 11 07 10 AM](https://user-images.githubusercontent.com/23535264/111079063-89c0e800-84b5-11eb-82d8-412b905f5294.png)
While the second query tab acknowledges the "success" of both queries, the first one does not. It appears that the query is still running. (see the three dots which continue to refresh).
![Screen Shot 2021-03-14 at 11 08 39 AM](https://user-images.githubusercontent.com/23535264/111079086-a78e4d00-84b5-11eb-9bf2-979ef3a8fa35.png)

When you attempt to use the Send to Dashboard button, only one of the queries is saved.

The workaround is to edit the resulting dashboard cell by cutting/pasting the second query into a new tab. 

Interestingly, once both queries are present within the cell on a dashboard, the first tab seems to report "unsubmitted" consistently as it's status while the second query tab's status changes from unsubmitted to success when changing query parameters such as time.
![Screen Shot 2021-03-14 at 11 12 35 AM](https://user-images.githubusercontent.com/23535264/111079208-356a3800-84b6-11eb-82fb-e5225965478d.png)
![Screen Shot 2021-03-14 at 11 12 28 AM](https://user-images.githubusercontent.com/23535264/111079209-3602ce80-84b6-11eb-9f75-44bcc7fbd33b.png)

**Comment by sranka** [comment]
Technically, there are two issues described herein:

1. There is just one [queryStatus](https://github.com/influxdata/chronograf/blob/eaa481d50296bea616f6b9c33a6487b921411cb7/ui/src/shared/components/TimeMachine/TimeMachine.tsx#L135), which is now associated with the latest query tab. As a consequence, the query status becomes "unsubmitted" or "running" when switching the tabs. To fix this, each tab would first require its own status. This is an architecture issue that exists probably since multiple tabs were introduced.

2. The 'Send to dashboard' functionality now sends an active tab query to a dashboard. To meet the expectation of this issue, it also has to allow adding all queries. It has to depend on the user choice of a new `Active Query | All <number> Queries` toggle that would also let the user know what queries are added, `Active Query` would be the default choice.

**Comment by sranka** [comment]
The issue with misleading query status(1st in https://github.com/influxdata/chronograf/issues/5703#issuecomment-823775223) is now standalone in #5738
