### ISSUE TITLE
Flux query builder is unable load buckets schema

### ISSUE THREAD

**Issue by tomklapka** [influxdata/chronograf#5721]
__Steps to reproduce:__
1. Connect to InfluxDB Enterprise 1.9.0rc1 source
2. Open Data Explore page
3. Switch to Flux query builder

__Expected behavior:__
Errorless loading of available buckets.

__Actual behavior:__
Flux Data explorer is unable to load bucket schema.

__Environment info:__

* Chronograf version: 202104010831~nightly (git: 7815527b1b25692a527154b403476720ecfeac63)
* Other relevant environment details: Ubuntu 16.04.5 LTS, InfluxDB Enterprise 1.9.0rc1

__Logs:__
```
Console errors:
src.a75e753d.js:1889 POST http://XXXXXXXX:8888/chronograf/v1/sources/2/proxy/flux?path=%2Fapi%2Fv2%2Fquery%3Forganization%3Ddefaultorgname 500 (Internal Server Error)

Error: error in building plan while starting program: buckets requires a remote host to be specified
    at v (src.a75e753d.js:1889)
    at XMLHttpRequest.c.onload (src.a75e753d.js:1889)
```
```
chronograf.log:
Internal Server Error" component=server method=POST remote_addr="XX.XXX.XXX.XX:51456" response_time=7.474655ms status=500
```

**Comment by lesam** [comment]
![Screenshot 2021-04-09 at 11 25 45 AM](https://user-images.githubusercontent.com/13399083/114203681-60fe0800-9926-11eb-9f72-bff6450f25f0.png)

Weird, it's working for me

**Comment by lesam** [comment]
(with latest InfluxDB Enterprise + ` docker run -p 8888:8888 chronograf:1.8.8` )

**Comment by timhallinflux** [comment]
I think there were some changes in 1.8.9.1 and/or 1.8.10 that looks at the version being reported by Enterprise that may be too strict?

**Comment by sranka** [comment]
I can reproduce this and I can also confirm that chronograf 1.8.8 works against the same instance of InfluxDB Enterprise 1.9.0-rc1 . Chronograf 1.8.8. uses v1 API (SHOW DATABASES and SHOW RETENTION POLICIE) to guess buckets. It was causing problems and it was changed in 1.8.9 to use a standard flux `buckets()` query.

The error `buckets requires a remote host to be specified` is thrown by InfluxDB Enterprise and it is related only to a simple `buckets()` flux query. Another simple flux script, such as  `from(bucket: "NOAA_water_database") |> range(start: 0)`, work fine.

I think that this issue is rather a defect of 1.9-rc01, or some misconfiguration in InfluxDB Enterprise. Anyway, somebody closer to InfluxDB Enterprise could possibly explain how to cope with the `buckets requires a remote host to be specified` error.

**Comment by lesam** [comment]
Yep this is a 1.9.0 issue:

1.8.4:
```
➜  ~ curl -XPOST "http://localhost:8086/api/v2/query" -d '{"type":"flux", "query":"buckets() "}'
#datatype,string,long,string,string,string,string,long
#group,false,false,false,false,true,false,false
#default,_result,,,,,,
,result,table,name,id,organizationID,retentionPolicy,retentionPeriod
,,0,_internal/monitor,,,monitor,604800000000000
,,0,telegraf/autogen,,,autogen,0
```

1.9.0 :
```
➜  ~ curl -XPOST "http://localhost:8086/api/v2/query" -d '{"type":"flux", "query":"buckets() "}'
{"error":"error in building plan while starting program: buckets requires a remote host to be specified"}
```

**Comment by lesam** [comment]
Error is specifically from here, this line did not exist in flux 0.65.0: https://github.com/influxdata/flux/blob/7d461e73fc93f2531f9c934da6358ac885a883f4/stdlib/influxdata/influxdb/buckets.go#L112

**Comment by lesam** [comment]
Fix above should close this out.

**Comment by lesam** [comment]
Influxdb issue: https://github.com/influxdata/influxdb/issues/21184

**Comment by sranka** [comment]
@tomklapka pls close after the fix is verified

**Comment by tomklapka** [comment]
Verified on 1.9.0rc2 Enterprise - OK
