### ISSUE TITLE
Unable to start chronograf docker image with "--resources-path" argument

### ISSUE THREAD

**Issue by MilanJaro** [influxdata/chronograf#5775]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

```
docker pull quay.io/influxdb/chronograf:1.8.10
docker run --name=chronograf -v $PWD:/usr/share/chronograf/resources quay.io/influxdb/chronograf:1.8.10 --resources-path=/usr/share/chronograf/resources
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "--resources-path=/usr/share/chronograf/resources": stat --resources-path=/usr/share/chronograf/resources: no such file or directory: unknown.
ERRO[0001] error waiting for container: context canceled
```

__Expected behavior:__
Chronograf docker image should start and load resources in the directory. The "--resources-path" is documented and should work in v1.8.10. The same worked in version 1.8.8

__Actual behavior:__
Chronograf docker image will not start and print this error message ->

docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "--resources-path=/usr/share/chronograf/resources": stat --resources-path=/usr/share/chronograf/resources: no such file or directory: unknown.
ERRO[0001] error waiting for container: context canceled

Directory "/usr/share/chronograf/resources" is not created in image. I have tried to put into docker arguments another directory, existing in the image, such as "/mnt", but the behaviour is exactly the same. 

__Environment info:__

* Chronograf version:  1.8.10
* Other relevant environment details: Linux ubuntu 18.04 LTS
__Config:__
n/a

**Comment by sranka** [comment]
Thank you for reporting an issue. Environment variables should be used to parameterize dockerized applications, in this case the environment variable is named `RESOURCES_PATH` . This works:

```
docker run -p 8888:888 --name=chronograf -v $PWD:/usr/share/chronograf/resources -e RESOURCES_PATH=/usr/share/chronograf/resources quay.io/influxdb/chronograf:1.8.10
```

The dockerfile didn't change since 1.8.8, maybe that the docker itself now better distinguish between entrypoint and cmd. The details are in https://github.com/influxdata/chronograf/blob/master/Dockerfile. The root cause is that `--resources-path=/usr/share/chronograf/resources` completely overrides dockerfile CMD.
