### ISSUE TITLE
Log viewer - 

### ISSUE THREAD

**Issue by Iszy-Ami** [influxdata/chronograf#5779]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1.  When click on Log Viewer
2. Setup connection with database
3. type an expression on the search log which does not exist 

__Expected behavior:__
expecting message: expression can't find or does not exist

__Actual behavior:__
It keeps searching
<img width="648" alt="Screenshot 2021-06-24 at 8 58 40" src="https://user-images.githubusercontent.com/56554624/123217510-ef683b80-d4ca-11eb-85ef-a65be4efbb62.png">

__Environment info:__

* Chronograf version: 1.8.10
* Other relevant environment details: InfluxDB v1

**Comment by sranka** [comment]
The Log Viewer (since its beginning) periodically polls InfluxDB for new log items, but the time is running ... what is not available now, can be available in the near future... it keeps searching forever. Changing the state to signalize empty results might require to reimplement the functionality or rethink the design.
