### ISSUE TITLE
When I change period to more than 1h, Flux chart does not show more than last 15min of data

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/chronograf#5819]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Define dashboard with 2 charts, one Flux and the other IQL based, both define the same query
2. [optional] Set Period in drop down to last 5, 15 minutes to check that both the charts show same results respectively to the value in the dropdown
3. Now increase Period to 1h, or more.

![image](https://user-images.githubusercontent.com/8028110/135273969-3981d8de-f87d-430d-a1f8-d08dc8f64c54.png)

```js
from(bucket: "telegraf/autogen")
  |> range(start: dashboardTime) 
  |> filter(fn: (r) => r._measurement == "cpu" and (r._field == "usage_idle") and (r.cpu == "cpu-total"))
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
```

```sql
SELECT mean("usage_idle") AS "mean_usage_idle" FROM "telegraf"."autogen"."cpu" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "cpu"='cpu-total' GROUP BY time(:interval:) FILL(null)
```
__Expected behavior:__
Describe what you expected to happen.

Both the charts should display same data within the period. 

__Actual behavior:__
Describe What actually happened.

The Flux based chart keeps showing only the last 15 minutes.

__Environment info:__

* Chronograf version: 1.9.0

**Comment by sranka** [comment]
This issue happens when some data are missing in the requested time window. Both of your charts show the same data, but the Flux chart contains only a time-frame in which the data is available because you have set `createEmpty: false`. An equivalent query to InfluxQL would be with `createEmpty: true`.

```
from(bucket: "telegraf/autogen")
  |> range(start: dashboardTime) 
  |> filter(fn: (r) => r._measurement == "cpu" and (r._field == "usage_idle") and (r.cpu == "cpu-total"))
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)
```

When using `createEmpty: true`, the charts are then still not the same. A null (empty) value in a flux response data is replaced by 0 by chronograf UI, this is a defect:

![image](https://user-images.githubusercontent.com/16321466/135330460-2c73ee4d-0444-440c-b771-5d17ec3335bd.png)

**Comment by sranka** [comment]
Closing in favor of #5820 that uses equivalent InfluxQL/Flux queries
