### ISSUE TITLE
Few Feature enquiry and requests

### ISSUE THREAD

**Issue by gaurav-moonfroglabs** [influxdata/chronograf#589]
Can we create custom dashboards like we use to create in chronograf 1.0 and earlier.

Also i have seen is you have removed option of custom query written by user. So it is possible to do so by some mean or other.

And can we have custom tags because right now if you group by tags in query the name of tip is too big or we should have somewhere listed all tags and can select from them to highlight only that host data.

**Comment by goller** [comment]
Hi @gaurav-moonfroglabs, this issue is really helpful for us set the priority!

> Can we create custom dashboards like we use to create in chronograf 1.0 and earlier.

We plan to have support for custom dashboards before our stable release.  It's _possible_ to create a custom dashboard right now by creating a new layout JSON file.  We have some brief documentation here: https://github.com/influxdata/chronograf/blob/master/docs/LAYOUT.md
However, we do plan to implement UI to make dashboards.

> Also i have seen is you have removed option of custom query written by user. So it is possible to do so by some mean or other.

Currently, no, we don't have the custom query. We plan to have it again.  We've been thinking about the best way to handle custom queries. Look for it soon!

> And can we have custom tags because right now if you group by tags in query the name of tip is too big or we should have somewhere listed all tags and can select from them to highlight only that host data.

Here is how to filter tags:

<img width="430" alt="group-by" src="https://cloud.githubusercontent.com/assets/1922921/20457698/37be9690-ae56-11e6-945f-0b67598621e3.png">

If you expand the group by tag you're allowed to select individual tags.  This creates conditions in the where clause.  

Does this solve this issue?

**Comment by gaurav-moonfroglabs** [comment]
Hey,

Yes definitely the recommendation and information shared by you are helpful to me in solving some problem.

Regarding tags i think i was not clear enough above. So my question is : When you group by tag then the name on tip of data point on graph is too big. Can we have custom tag name to shorten it.

Also is it possible to remove all datapoint show while we hover over the graph and show it one point a time if we have multiple data lines. That way it gets much clear if we have multiple tags selected.

**Comment by goller** [comment]
Ah I see.  That's clever.  I see what you mean. I'll see what we can do

**Comment by nhaugo** [comment]
@gaurav-moonfroglabs customizable dashboards are on the roadmap. see issues #621 #622 #612 #620 #614 and #615 for more details. Feel free to add any additional feedback on those issues or here.

**Comment by alexpaxton** [comment]
@goller @nhaugo I love the idea of user specified names, the uber long names in the graph legend are kinda gnarly. I can wireframe this out

**Comment by nhaugo** [comment]
Closing this, all initial request have been broken down into smaller issues
