### ISSUE TITLE
No insight into tags from host dash

### ISSUE THREAD

**Issue by unixninja92** [influxdata/chronograf#592]
Just the hostname isn't very helpful for me as most of my hostnames  are just ip addresses. It would be nice to see custom tags and configure which tags you can see. Both on the host dash in the table and on the host's page.

**Comment by goller** [comment]
Hey there @unixninja92, one way to handle this issue is it modify your telegraf configuration's "hostname" option:  https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#agent-configuration

Specifically, it says: ```hostname: Override default hostname, if empty use os.Hostname().```

However, I really like the idea that it would be possible to configure the table to include tag information for both the host dashboard and the layouts.  We've been kicking around ideas about how we want to customize our dashboards, so, this suggestion is really timely!

**Comment by unixninja92** [comment]
We are deploying Telegraf using cloud formation and auto scaling groups, so having the ip address is pretty useful, but just the ip alone isn't.

**Comment by goller** [comment]
Gotcha, yeah that makes total sense.

**Comment by nhaugo** [comment]
This is in our todo list, but isn't scheduled quite yet.

**Comment by hasselrot** [comment]
Any news on this? 
Having a "tag" field on the host dashboard would be extremely helpful for us.
We also have lots and lots of servers with randomly generated hostnames. 
Or hostnames that are identical over multiple environments. It gets messy very quickly.

**Comment by nhaugo** [comment]
It is still in the plans, but hasn't hit the committed backlog yet. Sorry about not having something more specific.

**Comment by russorat** [comment]
closing due to age. if needed, please reopen in https://github.com/influxdata/influxdb repo.
