### ISSUE TITLE
Annotations - Make it possible to mark events on timeline

### ISSUE THREAD

**Issue by agrrh** [influxdata/chronograf#650]
Hello!

At first, thank you for the great software.

I'd like to propose you to add some kind of **"events" mechanism**:

So, executing something like this:

```
curl \
  -X POST\
  --data '{"title": "#commit deployed", "tags": ["project-3"]}' \
  http://{chronograf|influxdb}/some/path
```

Should result in:

- **Vertical line**, titled with "#commit deployed"
- Drawn on each visualization which is tagged as "project-3" - related

This should **make it easier to read the graphs**, to compare it with real world, user would be able to understand:

- How different components of the system are dependent to each other
- Which consequences some actions in the past led to in present

Thank you for your time.

**Comment by goller** [comment]
@agrrh I really like this idea.  We plan to do this for sure.   I think it is really important to be able to correlate events with trends in the data.

Our rendering of events will not only support your use case, but, also render when alerts have been created by `kapacitor`.

**Comment by alexpaxton** [comment]
This sounds awesome

**Comment by nhaugo** [comment]
See Grafana annotations: http://docs.grafana.org/reference/annotations/ for reference

**Comment by alexpaxton** [comment]
Here's a rough idea:

**Right click to annotate**
![annotate-1](https://cloud.githubusercontent.com/assets/2433762/23242301/e5c79a18-f92c-11e6-8d6d-28824b6d19b9.png)

**Popover for creating a new annotation**
Has an option to add to all graphs at the same timestamp
![annotate-2](https://cloud.githubusercontent.com/assets/2433762/23242319/fc693876-f92c-11e6-8c1d-e0de0118e5b9.png)

**Existing Annotations**
On hover the label appears in the legend. Might want to limit the length of label user input for aesthetic purposes. Right click an annotation to edit it
![annotate-4](https://cloud.githubusercontent.com/assets/2433762/23242357/24befbbc-f92d-11e6-8869-a22d1af773b4.png)

**Edit Mode**
Delete instead of cancel
![annotate-3](https://cloud.githubusercontent.com/assets/2433762/23242368/38066cc8-f92d-11e6-8945-b5ce500ea075.png)

### Other considerations

- Do users want to change the timestamp of a market retroactively?
- How valuable is it to offer different annotation colors (or types)?
- Would it be valuable to see all annotations at once in table or list view?

**Comment by DaveMSchmitz** [comment]
This would be a really useful feature! Any updates?

**Comment by nhaugo** [comment]
Proposal 
When a dashboard is launched a query will check the chronograf.autogen.annotations table for presence of annotations in the `:dashtime:` for the cells in the dashboard. If the cell id exists, the cell should mark itself (for the time the dashboard is loaded, not via the ui) as having annotations.

If a cell has annotations, then each query should also query chronograf.autogen.annotations and any annotations should be rendered.

The annotation scheme should be
annotation,type=<some type>,id=<some id>,cell=<some cell id>,start_time=<start time>,end_time=<end of span> deleted=<true/false>,name=<the name of the annotation> influx_time_stamp

• Type: a free form, we will probably support various types in the future but will have no effect initially
• Id: a guid
• cell: The cell the annotation is tied to, if it is tied to multiple cells then there should be one entry per cell
• start_time: is the initial point
• end_time: if the annotation is a time span then the end time, otherwise 0
• deleted: to remove annotations an entry should be added with annotation_id, the cell id and deleted=true, when queried if there are more than one entry for an annotation chronograf should check for the oldest entry, if it has the deleted flag it should not be displayed.
• Name the name of the annotation

**Comment by 121watts** [comment]
```
{
    type: <string>,
    id: <guid>,
    time: <unix nano>,
    duration: <nanos>,
    text: <string>, 
}
```

**Comment by alexpaxton** [comment]
Almost done with the UI for this feature, dropping a checklist here to keep track of the remaining items

- [ ] Prevent annotation tooltip from appearing beneath the page header
- [ ] Style the `Delete` annotation button
- [ ] Fix the issue in which you can create two legends at the same time
- [ ] Prevent legend from appearing when editing annotations
- [ ] User can mouse over the window between endpoints and see a tooltip
- [ ] Render a window when the start and endpoints are outside the time range
- [ ] Delete a range and associated endpoints from endpoint

**Comment by nhaugo** [comment]
@goller todo, add a cell tag to the backend

**Comment by alexpaxton** [comment]
Got some feedback that warrants some more design

- How to display multiple annotations at the same timestamp?
- How to handle annotation tooltips when items are stacked? AKA what if there are multiple overlapping windows?

- Snap new timestamps to existing timestamps?

**Comment by hauleth** [comment]
Ideally there also would be HTTP API that would allow adding events dynamically, like new deployment added on each application startup or integration with other tools like Sentry (annotation on each error).

**Comment by goller** [comment]
@hauleth YES!! Here is my work around the annotations store:

https://github.com/influxdata/chronograf/tree/feature/annotation-store

Basically, through chronograf's API you'll be able to create/read/update/delete the annotations.  

Additionally, you can add annotations to influxdb itself using the schema we have come up with.  So, adding events dynamically is _exactly_ a use case we want to support.

I need to add more documentation around both the REST API and the InfluxDB schema.

**Comment by russorat** [comment]
awesome!

**Comment by Vigerus** [comment]
Hey,

I found this thread while struggling with my charts. Could i get some help combining:

`SELECT "value" FROM "unittest"."autogen"."cache_size" WHERE time > :dashboardTime:`

Visualization Type: Line

with shown events:

SELECT "text" FROM "unittest"."autogen"."events" WHERE time > :dashboardTime:

Can i create the "so called" annotations straight from the query?
