### ISSUE TITLE
Apps no longer show in host list view

### ISSUE THREAD

**Issue by nhaugo** [influxdata/chronograf#716]
The list of running applications on a host does not show in host list view, however, when clicking on a host i see the graphs i would expect for the applications that are running on the host.

**Comment by 121watts** [comment]
According to git bisect this is the offending commit :

```
06cdd47d475b481d7ef38141b94c350e107596f3 is the first bad commit
commit 06cdd47d475b481d7ef38141b94c350e107596f3
Author: Tim Raymond <tim@timraymond.com>
Date:   Thu Dec 8 14:19:55 2016 -0500

    Use `system` metrics to indicate host status

    This uses the `uptime` field collected by Telegraf in the `system`
    measurement to determine if a Host is currently up or down. We can
    determine if a host is down by using group by with a fill(0) and looking
    for zero values.

:040000 040000 0bba1f9e6ca1c6de327443f692da2002506a955a b1d5241c5cb741226e783783ac8f9d281a05efb0
```
@timraymond

**Comment by timraymond** [comment]
So, I couldn't find anything that made sense in that commit since that work was essentially reverted by later commits. For science, I bisected as well and it implicated this commit:

```
9dc8e02b1d8a3baadc6c8679634ad50a055f1254 is the first bad commit
commit 9dc8e02b1d8a3baadc6c8679634ad50a055f1254
Author: Will Piers <willpiers@influxdb.com>
Date:   Thu Dec 1 16:31:21 2016 -0800

    Refactor HostsTable for fun and SPEED

```

This makes more sense because if you filter the list and remove the filtering, apps start appearing, so it's something to do with components refusing an update when the apps list gets updated asynchronously. I'll explore this and see what shakes out. However, @121watts, I'm curious why we didn't arrive at the same commit. My methodology was to kill and restart Webpack, rebuild Chronograf, and kill browser caches at each rebase step, then try to filter and unfilter the list to see the bug as described above.

**Comment by 121watts** [comment]
That's odd. My process was the same, but I could have missed a restart or
rebuild.  I am a lowly human.
